version: "3.7"

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - agr-literature-db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
 
  pgadmin:
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PSQL_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8882:80"
    volumes:
      - agr-pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  
volumes:
  agr-literature-db-data:
  agr-pgadmin-data:
