version: "3.7"

services:
  postgres:
    container_name: agr-literature-test-pg
    hostname: agr-test-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: literature-test
      POSTGRES_PORT: ${PSQL_PORT}
    ports:
     - "5432:5432"
    volumes:
      - "agr-literature-test-pg-data:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql.conf"
    networks:
      - agr-literature-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # agr_literature:
  #   container_name: agr-literature-app
  #   hostname: agr-test-literature-app
  #   restart: always
  #   image: ${REG}/agr_literature_app:latest
  #   networks:
  #     - agr-literature
  #   depends_on:
  #     - postgres


volumes:
  agr-literature-test-pg-data:

networks:
  agr-literature-test:
