version: "3.7"

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - agr-literature-db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - agr-literature

  pgadmin:
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your@email.com
      PGADMIN_DEFAULT_PASSWORD: ${PSQL_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8882:80"
    volumes:
      - agr-pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - agr-literature

  elasticsearch:
    container_name: agr-literature-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - node.name=aws-literature-es1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - agr-es-data:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - agr-literature

  agr_literature:
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_literature_run:latest
    ports:
      - 49160:8080
    networks:
      - agr-literature

volumes:
  agr-literature-db-data:
  agr-pgadmin-data:
  agr-es-data:

networks:
  agr-literature:
