version: "3.7"

services:
  postgres:
    image: postgres:13.1-alpine
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_PORT: ${PSQL_PORT}
    volumes:
      - "agr-literature-pg-data:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql.conf"
    networks:
      - agr-literature
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      postgres -c config_file=/etc/postgresql.conf


  pgadmin:
    image: dpage/pgadmin4:5.1
    hostname: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8882:81"
    volumes:
      - "agr-literature-pgadmin-data:/var/lib/pgadmin"
    networks:
      - agr-literature
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: elasticsearch
    restart: always
    environment:
      - node.name=aws-literature-es1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "agr-literature-es-data:/usr/share/elasticsearch/data"
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
    networks:
      - agr-literature

  initdb:
    build:
      context: .
      dockerfile: docker/initdb.dockerfile
    hostname: initdb
    networks:
      - agr-literature
    depends_on:
      - postgres
    restart: on-failure

  pgsync:
    build:
      context: .
      dockerfile: docker/pgsync.dockerfile
    hostname: pgsync
    networks:
      - agr-literature
    volumes:
      - "./pgsync_schema.json:/src/app/pgsync_schema.json"
      - "./.env:/usr/local/lib/.env"
    depends_on:
      - initdb
      - elasticsearch
      - redis
    restart: on-failure

  redis:
    image: "redis:alpine"
    hostname: redis
    restart: always
    command: redis-server --requirepass "${REDIS_AUTH}"
    ports:
     - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      - agr-literature

  api:
    restart: always
    build:
      context: .
      dockerfile: docker/api.dockerfile
      args:
        REG: ${REG}
        TAG: ${TAG}
        ALLIANCE_RELEASE: ${ALLIANCE_RELEASE}
        AWS_SECRET_ACCESS_KEY: "$aws_secret_access_key"
        AWS_ACCESS_KEY_ID: "$aws_access_key_id"
        OKTA_CLIENT_ID: "$okta_client_id"
        OKTA_CLIENT_SECRET: "$okta_client_secret"
    hostname: literature_api
    ports:
      - "${API_PORT}:8080"
    networks:
      - agr-literature
    depends_on:
      - postgres

  xml_processing:
    restart: always
    build:
      context: .
      dockerfile: docker/xml_processing.dockerfile
      args:
        REG: ${REG}
        ALLIANCE_RELEASE: ${ALLIANCE_RELEASE}
    hostname: literature_xml_processing
    environment:
      API_PORT: "${API_PORT}"
      PYTHONPATH: "/usr/local/bin/src/literature/src/xml_processing"
      XML_PATH: "${XML_PATH}"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      OKTA_CLIENT_ID: "$OKTA_CLIENT_ID"
      OKTA_CLIENT_SECRET: "$OKTA_CLIENT_SECRET"
      ENV_STATE: "${ENV_STATE}"
      REG: "${REG}"
    networks:
      - agr-literature
    volumes:
      - agr-logs:/logs
    depends_on:
      - api

  tests:
    build:
      context: .
      dockerfile: docker/tests.dockerfile
      args:
        REG: ${REG}
        ALLIANCE_RELEASE: ${ALLIANCE_RELEASE}
    hostname: tests
    environment:
      API_PORT: "${API_PORT}"
      PYTHONPATH: "/usr/local/bin/src/literature/src/xml_processing"
      XML_PATH: "${XML_PATH}"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      OKTA_CLIENT_ID: "$OKTA_CLIENT_ID"
      OKTA_CLIENT_SECRET: "$OKTA_CLIENT_SECRET"
      ENV_STATE: "${ENV_STATE}"
      REG: "${REG}"
    networks:
      - agr-literature

  dev_app:
    restart: always
    build:
      context: .
      dockerfile: docker/dev-image.dockerfile
      args:
        REG: ${REG}
        TAG: ${TAG}
    hostname: dev_app
    environment:
      API_PORT: "${API_PORT}"
      PYTHONPATH: "/usr/local/bin/src/literature/src/xml_processing"
      XML_PATH: "${XML_PATH}"
      AWS_SECRET_ACCESS_KEY: "$aws_secret_access_key"
      AWS_ACCESS_KEY_ID: "$aws_access_key_id"
      OKTA_CLIENT_ID: "$okta_client_id"
      OKTA_CLIENT_SECRET: "$okta_client_secret"
      ENV_STATE: "${ENV_STATE}"
      REG: "${REG}"
    networks:
      - agr-literature
    volumes:
      - agr-logs:/logs
    depends_on:
      - api

volumes:
  agr-literature-pg-data:
  agr-literature-redis-data:
  agr-literature-pgadmin-data:
  agr-literature-es-data:
  agr-logs:

networks:
  agr-literature:
