version: "3.7"

services:
  postgres:
    container_name: agr-literature-test-pg
    hostname: agr-test-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: literature-test
      POSTGRES_PORT: 5432
    ports:
     - "5432:5432"
    volumes:
      - "agr-literature-test-pg-data:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql.conf"
    networks:
      - agr-literature-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  agr-literature-test-pg-data:

networks:
  agr-literature-test:
