version: "3.7"
services:
  postgres:
    container_name: agr-literature-test-pg
    hostname: agr-test-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: literature-test
      POSTGRES_PORT: 5432
    volumes:
      - "agr-literature-test-pg-data:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql.conf"
    networks:
      - agr-literature-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # initdb:
  #   container_name: agr-literature-initdb
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.initdb.env
  #   networks:
  #     - agr-literature-test
  #   depends_on:
  #     - postgres
  #   restart: on-failure

  agr_literature:
    container_name: agr-literature-app-test
    hostname: agr-test-app
    restart: always
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_literature_app_test:latest
    environment:
      API_PORT: 8080
      PYTHONPATH: "/usr/local/bin/src/literature/src/xml_processing"
      XML_PATH: "/usr/local/bin/src/literature/src/xml_processing/tests/"
    ports:
        - "8080:8080"
    networks:
        - agr-literature-test
    volumes:
        - agr-logs:/logs
    depends_on:
        - postgres

volumes:
  agr-literature-test-pg-data:
  agr-logs:
   
networks:
  agr-literature-test:
