version: "3.7"

services:
  pg:
    container_name: agr-literature-pg
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: ${PSQL_PASSWORD}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - agr-literature-db-data:/var/lib/postgresql/data
      - $PWD/postgresql.conf:/etc/postgresql.conf
    networks:
      - agr-literature

  pgadmin:
    container_name: agr-literature-pgadmin
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8882:81"
    volumes:
      - agr-pgadmin-data:/var/lib/pgadmin
    networks:
      - agr-literature

  elasticsearch:
    container_name: agr-literature-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - node.name=aws-literature-es1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - agr-es-data:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - agr-literature

  redis:
    container_name: agr-literature-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_AUTH}
    ports:
     - "6379:6379"
    volumes:
      - agr-literature-redis-data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      - agr-literature

  agr_literature:
    container_name: agr-literature-app
    image: ${REG}/agr_literature_run:latest
    ports:
      - 49160:8080
    networks:
      - agr-literature

volumes:
  agr-literature-db-data:
  agr-literature-redis-data:
  agr-pgadmin-data:
  agr-es-data:

networks:
  agr-literature:
