[pytest]
testpaths=tests/api
addopts =
    --ignore=tests/api/test_cross_ref.py
    --ignore=tests/api/test_editor.py
    --ignore=tests/api/test_mod_ref_type.py
    --ignore=tests/api/test_ref_relation.py
    --ignore=tests/api/test_reference.py
    --ignore=tests/api/test_reference_mod_md5sum.py
    --ignore=tests/api/test_referencefile.py
    --ignore=tests/api/test_referencefile_mod.py
    --ignore=tests/api/test_resource.py
    --ignore=tests/api/test_resource_descriptor.py
    --ignore=tests/api/test_search.py
    --ignore=tests/api/test_search_dates.py
    --ignore=tests/api/test_sort.py
    --ignore=tests/api/test_topic_entity_tag.py
    --ignore=tests/api/test_topic_entity_tag_source.py
    --ignore=tests/api/test_workflow_automation.py
    --ignore=tests/api/test_workflow_tag.py
