#!/usr/bin/env sh

export PGPASSWORD=${PSQL_PASSWORD}
psql -U ${PSQL_USERNAME} -p ${PSQL_PORT} -h ${PSQL_HOST} -c "\set AUTOCOMMIT on\nDROP DATABASE \"${PSQL_DATABASE}\"; CREATE DATABASE \"${PSQL_DATABASE}\";"