"""
Fix FlyBase (FB) entity/gene extraction retry transitions.

Background
----------
The weekly cron ``check_wft_in_progress.py`` (extraction phase) resets stuck
entity/gene extraction tags back to "needed" by calling
``job_change_atp_code(db, reference_workflow_tag_id, 'on_retry')``. That runs the
matching ``WorkflowTransitionModel`` row's ``actions`` via ``sub_task_retry``,
which uses the checktype in the action string to decide which *main* status tag
to update.

FB's extraction ``on_retry`` rows were generated by ``SCRUM-4715.py``, which
hardcodes ``actions=['sub_task_retry::reference classification']`` for every
process it iterates -- including the entity-extraction pass. So the retry resets
the extraction sub-task tag correctly (failed/in progress -> needed) but then
mutates the *reference classification* main tag (ATP:0000165 family) instead of
the *entity extraction* main tag (ATP:0000172 family).

This one-off corrects those FB extraction ``on_retry`` rows so their action is
``sub_task_retry::entity extraction``. It is scoped strictly to FB extraction
transitions (transition_from within the entity-extraction descendant tree) so
legitimate reference-classification ``on_retry`` rows are left untouched. It is
idempotent (only touches rows still carrying the buggy action) and supports a
``--debug`` dry-run.

Note: re-running ``SCRUM-4715.py`` against FB would reintroduce this bug; that
generator should be fixed separately before it is re-run.
"""
import argparse
import logging

from agr_literature_service.api.crud.ateam_db_helpers import atp_get_all_descendants
from agr_literature_service.api.models import ModModel, WorkflowTransitionModel
from agr_literature_service.lit_processing.utils.sqlalchemy_utils import create_postgres_session

logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s', level=logging.INFO)
logger = logging.getLogger()

# entity extraction parents (ATP:0000172 family)
ENTITY_EXTRACTION_FAILED = 'ATP:0000187'       # entity extraction failed
ENTITY_EXTRACTION_IN_PROGRESS = 'ATP:0000190'  # entity extraction in progress

WRONG_ACTIONS = ['sub_task_retry::reference classification']
CORRECT_ACTIONS = ['sub_task_retry::entity extraction']


def get_fb_mod_id(db_session):
    mod = db_session.query(ModModel).filter(ModModel.abbreviation == 'FB').one_or_none()
    if mod is None:
        raise RuntimeError("Could not find mod with abbreviation 'FB'")
    return mod.mod_id


def get_extraction_from_tags():
    """The valid ``transition_from`` curies for extraction on_retry rows:
    every failed/in-progress entity-extraction tag (parents + sub-task children).
    """
    tags = set(atp_get_all_descendants(ENTITY_EXTRACTION_FAILED, include_self=True))
    tags |= set(atp_get_all_descendants(ENTITY_EXTRACTION_IN_PROGRESS, include_self=True))
    if not tags:
        raise RuntimeError(
            "Could not resolve entity-extraction descendants from the A-team "
            "ontology; aborting rather than risk an unscoped update")
    return tags


def fix_fb_entity_extraction_retry_actions(db_session, debug=True):
    fb_mod_id = get_fb_mod_id(db_session)
    from_tags = get_extraction_from_tags()

    if debug:
        logger.info(f"Resolved {len(from_tags)} entity-extraction transition_from tag(s): "
                    f"{sorted(from_tags)}")
        all_retry = db_session.query(WorkflowTransitionModel).filter(
            WorkflowTransitionModel.mod_id == fb_mod_id,
            WorkflowTransitionModel.condition.contains('on_retry')).all()
        logger.info(f"All {len(all_retry)} FB on_retry row(s) in DB:")
        for row in all_retry:
            in_tree = row.transition_from in from_tags
            logger.info(
                f"  {row.transition_from} -> {row.transition_to} "
                f"(condition={row.condition!r}, actions={row.actions!r}, "
                f"in_extraction_tree={in_tree})")

    rows = db_session.query(WorkflowTransitionModel).filter(
        WorkflowTransitionModel.mod_id == fb_mod_id,
        WorkflowTransitionModel.condition.contains('on_retry'),
        WorkflowTransitionModel.transition_from.in_(from_tags),
        WorkflowTransitionModel.actions == WRONG_ACTIONS).all()

    logger.info(f"Found {len(rows)} FB extraction on_retry row(s) with the wrong action")
    for row in rows:
        logger.info(
            f"{'[debug] ' if debug else ''}"
            f"{row.transition_from} -> {row.transition_to} (condition={row.condition}): "
            f"{WRONG_ACTIONS} -> {CORRECT_ACTIONS}")
        if not debug:
            row.actions = CORRECT_ACTIONS

    if debug:
        logger.info("Debug mode: no changes committed")
    else:
        db_session.commit()
        logger.info(f"Updated {len(rows)} row(s)")


def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-d', '--debug', help='run in debug mode, just print', action='store_true')
    args = parser.parse_args()
    db_session = create_postgres_session(False)
    fix_fb_entity_extraction_retry_actions(db_session, debug=args.debug)


if __name__ == "__main__":
    main()
