"""editors table renamed editor

Revision ID: 1862a0356ece
Revises: d9c48be2f4d2
Create Date: 2022-05-02 09:48:47.760231

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1862a0356ece'
down_revision = 'd9c48be2f4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('editors', 'editor')
    # its sequence
    op.execute('ALTER SEQUENCE editors_editor_id_seq RENAME TO editor_editor_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX editors_pkey RENAME TO editor_pkey')
    op.execute('ALTER INDEX ix_editors_resource_id RENAME TO ix_editor_resource_id')
    # Foreign Key Constraints?
    #  thse maybe okay as the keys are the same???

    # The table version
    op.rename_table('editors_version', 'editor_version')
    # It has NO sequences.
    # ITs indexes
    op.execute('ALTER INDEX editors_version_pkey RENAME TO editor_version_pkey')
    op.execute('ALTER INDEX ix_editors_version_end_transaction_id RENAME TO ix_editor_version_end_transaction_id')
    op.execute('ALTER INDEX ix_editors_version_operation_type RENAME TO ix_editor_version_operation_type')
    op.execute('ALTER INDEX ix_editors_version_resource_id RENAME TO ix_editor_version_resource_id')
    op.execute('ALTER INDEX ix_editors_version_transaction_id RENAME TO ix_editor_version_transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('editor', 'editors')
    # its sequence
    op.execute('ALTER SEQUENCE editor_editor_id_seq RENAME TO editors_editor_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX editor_pkey RENAME TO editors_pkey')
    op.execute('ALTER INDEX ix_editor_resource_id RENAME TO ix_editors_resource_id')
    # Foreign Key Constraints?
    #  thse maybe okay as the keys are the same???

    # The table version
    op.rename_table('editors_version', 'editor_version')
    # It has NO sequences.
    # ITs indexes
    op.execute('ALTER INDEX editor_version_pkey RENAME TO editors_version_pkey')
    op.execute('ALTER INDEX ix_editor_version_end_transaction_id RENAME TO ix_editors_version_end_transaction_id')
    op.execute('ALTER INDEX ix_editor_version_operation_type RENAME TO ix_editors_version_operation_type')
    op.execute('ALTER INDEX ix_editor_version_resource_id RENAME TO ix_editors_version_resource_id')
    op.execute('ALTER INDEX ix_editor_version_transaction_id RENAME TO ix_editors_version_transaction_id')
    # ### end Alembic commands ###
