"""add_first_initial_column

Revision ID: 63f9353737ad
Revises: a68cb3e25cb2
Create Date: 2023-05-14 20:43:37.289649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f9353737ad'
down_revision = 'a68cb3e25cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('first_initial', sa.String(), nullable=True))
    op.add_column('author_version', sa.Column('first_initial', sa.String(), autoincrement=False, nullable=True))
    op.add_column('author_version', sa.Column('first_initial_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_version', 'first_initial_mod')
    op.drop_column('author_version', 'first_initial')
    op.drop_column('author', 'first_initial')
    # ### end Alembic commands ###
