"""xref same curie constraints

Revision ID: 87542e01f417
Revises: 948b3ffaaf2c
Create Date: 2023-06-22 19:00:19.965290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87542e01f417'
down_revision = '948b3ffaaf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_curie_ref', 'cross_reference', ['curie', 'reference_id'], unique=True, postgresql_where=sa.text('reference_id IS NOT NULL'))
    op.create_index('idx_curie_res', 'cross_reference', ['curie', 'resource_id'], unique=True, postgresql_where=sa.text('resource_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_curie_res', table_name='cross_reference')
    op.drop_index('idx_curie_ref', table_name='cross_reference')
    # ### end Alembic commands ###
