"""updated species constraints

Revision ID: 4ab9020aaf62
Revises: debffc478a32
Create Date: 2023-05-19 19:20:08.200805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ab9020aaf62'
down_revision = 'debffc478a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic_entity_tag', 'species',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_unique_topic_tag_with_species', 'topic_entity_tag', ['reference_id', 'topic', 'species'], unique=True, postgresql_where=sa.text('entity_type IS NULL AND species IS NOT NULL'))
    op.create_index('ix_unique_topic_tag_without_species', 'topic_entity_tag', ['reference_id', 'topic'], unique=True, postgresql_where=sa.text('entity_type IS NULL AND species IS NULL'))
    op.drop_index('ix_unique_topic_tag', table_name='topic_entity_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_topic_tag', 'topic_entity_tag', ['reference_id', 'topic', 'species'], unique=True)
    op.drop_index('ix_unique_topic_tag_without_species', table_name='topic_entity_tag')
    op.drop_index('ix_unique_topic_tag_with_species', table_name='topic_entity_tag')
    op.alter_column('topic_entity_tag', 'species',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
