"""topic entity model sources and qualifiers

Revision ID: debffc478a32
Revises: 63f9353737ad
Create Date: 2023-05-17 15:50:56.357040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'debffc478a32'
down_revision = '63f9353737ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_entity_tag_qualifier_version',
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('topic_entity_tag_qualifier_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('topic_entity_tag_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('qualifier', sa.String(), autoincrement=False, nullable=True),
    sa.Column('qualifier_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('topic_entity_tag_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('qualifier_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('qualifier_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mod_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('topic_entity_tag_qualifier_id', 'transaction_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_qualifier_version_end_transaction_id'), 'topic_entity_tag_qualifier_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_qualifier_version_mod_id'), 'topic_entity_tag_qualifier_version', ['mod_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_qualifier_version_operation_type'), 'topic_entity_tag_qualifier_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_qualifier_version_topic_entity_tag_id'), 'topic_entity_tag_qualifier_version', ['topic_entity_tag_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_qualifier_version_transaction_id'), 'topic_entity_tag_qualifier_version', ['transaction_id'], unique=False)
    op.create_table('topic_entity_tag_source_version',
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('topic_entity_tag_source_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('topic_entity_tag_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('source', sa.String(), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.String(), autoincrement=False, nullable=True),
    sa.Column('validated', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('validation_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('note', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('topic_entity_tag_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mod_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('confidence_level_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('validated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('validation_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('topic_entity_tag_source_id', 'transaction_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_source_version_end_transaction_id'), 'topic_entity_tag_source_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_version_mod_id'), 'topic_entity_tag_source_version', ['mod_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_version_operation_type'), 'topic_entity_tag_source_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_version_topic_entity_tag_id'), 'topic_entity_tag_source_version', ['topic_entity_tag_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_version_transaction_id'), 'topic_entity_tag_source_version', ['transaction_id'], unique=False)
    op.create_table('topic_entity_tag_qualifier',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('topic_entity_tag_qualifier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_entity_tag_id', sa.Integer(), nullable=False),
    sa.Column('qualifier', sa.String(), nullable=False),
    sa.Column('qualifier_type', sa.String(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_entity_tag_id'], ['topic_entity_tag.topic_entity_tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('topic_entity_tag_qualifier_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_qualifier_mod_id'), 'topic_entity_tag_qualifier', ['mod_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_qualifier_topic_entity_tag_id'), 'topic_entity_tag_qualifier', ['topic_entity_tag_id'], unique=False)
    op.create_table('topic_entity_tag_source',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('topic_entity_tag_source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_entity_tag_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_type', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.CheckConstraint('validated IS true AND validation_type IS NOT NULL OR validated IS false AND validation_type IS NULL', name='validation_type_not_null_when_validation_provided'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_entity_tag_id'], ['topic_entity_tag.topic_entity_tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('topic_entity_tag_source_id'),
    sa.UniqueConstraint('topic_entity_tag_id', 'mod_id', 'source', name='source_topic_entity_tag_unique')
    )
    op.create_index(op.f('ix_topic_entity_tag_source_mod_id'), 'topic_entity_tag_source', ['mod_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_topic_entity_tag_id'), 'topic_entity_tag_source', ['topic_entity_tag_id'], unique=False)
    op.drop_index('ix_topic_entity_tag_prop_topic_entity_tag_id', table_name='topic_entity_tag_prop')
    op.drop_table('topic_entity_tag_prop')
    op.drop_index('ix_topic_entity_tag_prop_version_end_transaction_id', table_name='topic_entity_tag_prop_version')
    op.drop_index('ix_topic_entity_tag_prop_version_operation_type', table_name='topic_entity_tag_prop_version')
    op.drop_index('ix_topic_entity_tag_prop_version_topic_entity_tag_id', table_name='topic_entity_tag_prop_version')
    op.drop_index('ix_topic_entity_tag_prop_version_transaction_id', table_name='topic_entity_tag_prop_version')
    op.drop_table('topic_entity_tag_prop_version')
    op.alter_column('reference_version', 'citation_id_mod',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('topic_entity_tag', sa.Column('entity', sa.String(), nullable=True))
    op.add_column('topic_entity_tag', sa.Column('entity_published_as', sa.String(), nullable=True))
    op.add_column('topic_entity_tag', sa.Column('entity_source', sa.String(), nullable=True))
    op.add_column('topic_entity_tag', sa.Column('species', sa.String(), nullable=False))
    op.alter_column('topic_entity_tag', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_unique_entity_tag', 'topic_entity_tag', ['reference_id', 'topic', 'entity_type', 'entity', 'entity_source', 'species'], unique=True, postgresql_where=sa.text('entity_type IS NOT NULL'))
    op.create_index('ix_unique_topic_tag', 'topic_entity_tag', ['reference_id', 'topic', 'species'], unique=True, postgresql_where=sa.text('entity_type IS NULL'))
    op.drop_column('topic_entity_tag', 'alliance_entity')
    op.drop_column('topic_entity_tag', 'taxon')
    op.drop_column('topic_entity_tag', 'mod_entity')
    op.drop_column('topic_entity_tag', 'new_entity')
    op.drop_column('topic_entity_tag', 'note')
    op.add_column('topic_entity_tag_version', sa.Column('entity', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('entity_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('entity_published_as', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('entity_published_as_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('entity_source', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('entity_source_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('species', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('species_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('topic_entity_tag_version', 'note_mod')
    op.drop_column('topic_entity_tag_version', 'new_entity_mod')
    op.drop_column('topic_entity_tag_version', 'alliance_entity')
    op.drop_column('topic_entity_tag_version', 'taxon')
    op.drop_column('topic_entity_tag_version', 'taxon_mod')
    op.drop_column('topic_entity_tag_version', 'alliance_entity_mod')
    op.drop_column('topic_entity_tag_version', 'mod_entity')
    op.drop_column('topic_entity_tag_version', 'new_entity')
    op.drop_column('topic_entity_tag_version', 'note')
    op.drop_column('topic_entity_tag_version', 'mod_entity_mod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_entity_tag_version', sa.Column('mod_entity_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('new_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('mod_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('alliance_entity_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('taxon_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('taxon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('alliance_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('new_entity_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('note_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('topic_entity_tag_version', 'species_mod')
    op.drop_column('topic_entity_tag_version', 'species')
    op.drop_column('topic_entity_tag_version', 'entity_source_mod')
    op.drop_column('topic_entity_tag_version', 'entity_source')
    op.drop_column('topic_entity_tag_version', 'entity_published_as_mod')
    op.drop_column('topic_entity_tag_version', 'entity_published_as')
    op.drop_column('topic_entity_tag_version', 'entity_mod')
    op.drop_column('topic_entity_tag_version', 'entity')
    op.add_column('topic_entity_tag', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag', sa.Column('new_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag', sa.Column('mod_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag', sa.Column('taxon', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag', sa.Column('alliance_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_unique_topic_tag', table_name='topic_entity_tag')
    op.drop_index('ix_unique_entity_tag', table_name='topic_entity_tag')
    op.alter_column('topic_entity_tag', 'entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('topic_entity_tag', 'species')
    op.drop_column('topic_entity_tag', 'entity_source')
    op.drop_column('topic_entity_tag', 'entity_published_as')
    op.drop_column('topic_entity_tag', 'entity')
    op.alter_column('reference_version', 'citation_id_mod',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_table('topic_entity_tag_prop_version',
    sa.Column('topic_entity_tag_prop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_entity_tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qualifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('topic_entity_tag_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('qualifier_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_created_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_updated_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('topic_entity_tag_prop_id', 'transaction_id', name='topic_entity_tag_prop_version_pkey')
    )
    op.create_index('ix_topic_entity_tag_prop_version_transaction_id', 'topic_entity_tag_prop_version', ['transaction_id'], unique=False)
    op.create_index('ix_topic_entity_tag_prop_version_topic_entity_tag_id', 'topic_entity_tag_prop_version', ['topic_entity_tag_id'], unique=False)
    op.create_index('ix_topic_entity_tag_prop_version_operation_type', 'topic_entity_tag_prop_version', ['operation_type'], unique=False)
    op.create_index('ix_topic_entity_tag_prop_version_end_transaction_id', 'topic_entity_tag_prop_version', ['end_transaction_id'], unique=False)
    op.create_table('topic_entity_tag_prop',
    sa.Column('topic_entity_tag_prop_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_entity_tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='topic_entity_tag_prop_created_by_fkey'),
    sa.ForeignKeyConstraint(['topic_entity_tag_id'], ['topic_entity_tag.topic_entity_tag_id'], name='topic_entity_tag_prop_topic_entity_tag_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='topic_entity_tag_prop_updated_by_fkey'),
    sa.PrimaryKeyConstraint('topic_entity_tag_prop_id', name='topic_entity_tag_prop_pkey')
    )
    op.create_index('ix_topic_entity_tag_prop_topic_entity_tag_id', 'topic_entity_tag_prop', ['topic_entity_tag_id'], unique=False)
    op.drop_index(op.f('ix_topic_entity_tag_source_topic_entity_tag_id'), table_name='topic_entity_tag_source')
    op.drop_index(op.f('ix_topic_entity_tag_source_mod_id'), table_name='topic_entity_tag_source')
    op.drop_table('topic_entity_tag_source')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_topic_entity_tag_id'), table_name='topic_entity_tag_qualifier')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_mod_id'), table_name='topic_entity_tag_qualifier')
    op.drop_table('topic_entity_tag_qualifier')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_transaction_id'), table_name='topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_topic_entity_tag_id'), table_name='topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_operation_type'), table_name='topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_mod_id'), table_name='topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_end_transaction_id'), table_name='topic_entity_tag_source_version')
    op.drop_table('topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_version_transaction_id'), table_name='topic_entity_tag_qualifier_version')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_version_topic_entity_tag_id'), table_name='topic_entity_tag_qualifier_version')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_version_operation_type'), table_name='topic_entity_tag_qualifier_version')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_version_mod_id'), table_name='topic_entity_tag_qualifier_version')
    op.drop_index(op.f('ix_topic_entity_tag_qualifier_version_end_transaction_id'), table_name='topic_entity_tag_qualifier_version')
    op.drop_table('topic_entity_tag_qualifier_version')
    # ### end Alembic commands ###
