"""valid_entity_type_dependencies

Revision ID: 7f029313b097
Revises: 2ceacbde8ac2
Create Date: 2023-11-29 21:03:26.391564

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7f029313b097'
down_revision = '2ceacbde8ac2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old check constraint
    op.drop_constraint('entity_entity_source_and_species_not_null_when_entity_type_provided', 'topic_entity_tag', type_='check')

    # Add the new check constraint
    op.create_check_constraint(
        'valid_entity_type_dependencies', 
        'topic_entity_tag',
        sa.sql.text("""
            (
                (entity_type IS NOT NULL AND entity IS NOT NULL AND entity_source IS NOT NULL AND species IS NOT NULL AND topic != 'ATP:0000123' AND entity_type != 'ATP:0000123')
                OR
                (topic = 'ATP:0000123' AND entity_type = 'ATP:0000123' AND entity_source IS NOT NULL AND species IS NULL)
                OR
                (entity_type IS NULL AND entity IS NULL AND entity_source IS NULL)
                OR
                (entity_type IS NOT NULL AND entity IS NULL AND entity_source IS NULL AND species IS NOT NULL AND negated IS TRUE)
            )
        """)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new check constraint
    op.drop_constraint('valid_entity_type_dependencies', 'topic_entity_tag', type_='check')

    # Re-add the old check constraint
    op.create_check_constraint(
        'entity_entity_source_and_species_not_null_when_entity_type_provided', 
        'topic_entity_tag',
        sa.sql.text("""
            (
                (entity_type IS NOT NULL AND entity IS NOT NULL AND entity_source IS NOT NULL AND species IS NOT NULL)
                OR
                (entity_type IS NULL AND entity IS NULL AND entity_source IS NULL)
                OR
                (entity_type IS NOT NULL AND entity IS NULL AND entity_source IS NULL AND species IS NOT NULL AND negated IS TRUE)
            )
        """)
    )
    # ### end Alembic commands ###
