"""remove mesh details versioning

Revision ID: 280506fb4595
Revises: ec20a747f6d3
Create Date: 2023-07-17 10:14:11.474769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280506fb4595'
down_revision = 'ec20a747f6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mesh_detail_version_end_transaction_id', table_name='mesh_detail_version')
    op.drop_index('ix_mesh_detail_version_operation_type', table_name='mesh_detail_version')
    op.drop_index('ix_mesh_detail_version_reference_id', table_name='mesh_detail_version')
    op.drop_index('ix_mesh_detail_version_transaction_id', table_name='mesh_detail_version')
    op.drop_table('mesh_detail_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesh_detail_version',
    sa.Column('mesh_detail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heading_term', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qualifier_term', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reference_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('heading_term_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('qualifier_term_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('mesh_detail_id', 'transaction_id', name='mesh_detail_version_pkey')
    )
    op.create_index('ix_mesh_detail_version_transaction_id', 'mesh_detail_version', ['transaction_id'], unique=False)
    op.create_index('ix_mesh_detail_version_reference_id', 'mesh_detail_version', ['reference_id'], unique=False)
    op.create_index('ix_mesh_detail_version_operation_type', 'mesh_detail_version', ['operation_type'], unique=False)
    op.create_index('ix_mesh_detail_version_end_transaction_id', 'mesh_detail_version', ['end_transaction_id'], unique=False)
    # ### end Alembic commands ###
