"""topic_ntt_tag_single_table

Revision ID: 929095dbc485
Revises: 280506fb4595
Create Date: 2023-08-11 01:51:55.547356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929095dbc485'
down_revision = '280506fb4595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_entity_tag_validation',
    sa.Column('validated_topic_entity_tag_id', sa.Integer(), nullable=False),
    sa.Column('validating_topic_entity_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['validated_topic_entity_tag_id'], ['topic_entity_tag.topic_entity_tag_id'], ),
    sa.ForeignKeyConstraint(['validating_topic_entity_tag_id'], ['topic_entity_tag.topic_entity_tag_id'], ),
    sa.PrimaryKeyConstraint('validated_topic_entity_tag_id', 'validating_topic_entity_tag_id')
    )
    op.add_column('topic_entity_tag', sa.Column('confidence_level', sa.String(), nullable=True))
    op.add_column('topic_entity_tag', sa.Column('negated', sa.Boolean(), nullable=False))
    op.add_column('topic_entity_tag', sa.Column('note', sa.String(), nullable=True))
    op.add_column('topic_entity_tag', sa.Column('topic_entity_tag_source_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_topic_entity_tag_source_id'), 'topic_entity_tag', ['topic_entity_tag_source_id'], unique=False)
    op.drop_index('ix_unique_entity_tag', table_name='topic_entity_tag')
    op.drop_index('ix_unique_topic_tag_with_species', table_name='topic_entity_tag')
    op.drop_index('ix_unique_topic_tag_without_species', table_name='topic_entity_tag')
    op.create_foreign_key(None, 'topic_entity_tag', 'topic_entity_tag_source', ['topic_entity_tag_source_id'], ['topic_entity_tag_source_id'], ondelete='CASCADE')
    op.add_column('topic_entity_tag_source', sa.Column('description', sa.String(), nullable=True))
    op.add_column('topic_entity_tag_source', sa.Column('evidence', sa.String(), nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('source_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_source_source_name'), 'topic_entity_tag_source', ['source_name'], unique=False)
    op.create_unique_constraint('topic_entity_tag_source_unique', 'topic_entity_tag_source', ['source_name', 'mod_id'])
    op.drop_index('ix_topic_entity_tag_source_topic_entity_tag_id', table_name='topic_entity_tag_source')
    op.drop_constraint('source_topic_entity_tag_unique', 'topic_entity_tag_source', type_='unique')
    op.drop_constraint('topic_entity_tag_source_topic_entity_tag_id_fkey', 'topic_entity_tag_source', type_='foreignkey')
    op.drop_column('topic_entity_tag_source', 'note')
    op.drop_column('topic_entity_tag_source', 'validation_value_author')
    op.drop_column('topic_entity_tag_source', 'topic_entity_tag_id')
    op.drop_column('topic_entity_tag_source', 'validation_value_curator')
    op.drop_column('topic_entity_tag_source', 'confidence_level')
    op.drop_column('topic_entity_tag_source', 'validation_value_curation_tools')
    op.drop_column('topic_entity_tag_source', 'negated')
    op.drop_column('topic_entity_tag_source', 'source')
    op.add_column('topic_entity_tag_source_version', sa.Column('description', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('evidence', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('evidence_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('source_name', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('source_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_source_version_source_name'), 'topic_entity_tag_source_version', ['source_name'], unique=False)
    op.drop_index('ix_topic_entity_tag_source_version_topic_entity_tag_id', table_name='topic_entity_tag_source_version')
    op.drop_column('topic_entity_tag_source_version', 'confidence_level_mod')
    op.drop_column('topic_entity_tag_source_version', 'note')
    op.drop_column('topic_entity_tag_source_version', 'validation_value_author')
    op.drop_column('topic_entity_tag_source_version', 'validation_value_curator_mod')
    op.drop_column('topic_entity_tag_source_version', 'validation_value_curator')
    op.drop_column('topic_entity_tag_source_version', 'topic_entity_tag_id')
    op.drop_column('topic_entity_tag_source_version', 'confidence_level')
    op.drop_column('topic_entity_tag_source_version', 'note_mod')
    op.drop_column('topic_entity_tag_source_version', 'topic_entity_tag_id_mod')
    op.drop_column('topic_entity_tag_source_version', 'validation_value_author_mod')
    op.drop_column('topic_entity_tag_source_version', 'source')
    op.drop_column('topic_entity_tag_source_version', 'validation_value_curation_tools')
    op.drop_column('topic_entity_tag_source_version', 'validation_value_curation_tools_mod')
    op.drop_column('topic_entity_tag_source_version', 'negated')
    op.drop_column('topic_entity_tag_source_version', 'negated_mod')
    op.drop_column('topic_entity_tag_source_version', 'source_mod')
    op.add_column('topic_entity_tag_version', sa.Column('confidence_level', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('confidence_level_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('negated', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('negated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('note', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('note_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_version', sa.Column('topic_entity_tag_source_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('topic_entity_tag_source_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_version_topic_entity_tag_source_id'), 'topic_entity_tag_version', ['topic_entity_tag_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_entity_tag_version_topic_entity_tag_source_id'), table_name='topic_entity_tag_version')
    op.drop_column('topic_entity_tag_version', 'topic_entity_tag_source_id_mod')
    op.drop_column('topic_entity_tag_version', 'topic_entity_tag_source_id')
    op.drop_column('topic_entity_tag_version', 'note_mod')
    op.drop_column('topic_entity_tag_version', 'note')
    op.drop_column('topic_entity_tag_version', 'negated_mod')
    op.drop_column('topic_entity_tag_version', 'negated')
    op.drop_column('topic_entity_tag_version', 'confidence_level_mod')
    op.drop_column('topic_entity_tag_version', 'confidence_level')
    op.add_column('topic_entity_tag_source_version', sa.Column('source_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('negated_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('negated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('validation_value_curation_tools_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('validation_value_curation_tools', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('validation_value_author_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('topic_entity_tag_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('note_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('confidence_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('topic_entity_tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('validation_value_curator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('validation_value_curator_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('validation_value_author', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('confidence_level_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_topic_entity_tag_source_version_topic_entity_tag_id', 'topic_entity_tag_source_version', ['topic_entity_tag_id'], unique=False)
    op.drop_index(op.f('ix_topic_entity_tag_source_version_source_name'), table_name='topic_entity_tag_source_version')
    op.drop_column('topic_entity_tag_source_version', 'source_name_mod')
    op.drop_column('topic_entity_tag_source_version', 'source_name')
    op.drop_column('topic_entity_tag_source_version', 'evidence_mod')
    op.drop_column('topic_entity_tag_source_version', 'evidence')
    op.drop_column('topic_entity_tag_source_version', 'description_mod')
    op.drop_column('topic_entity_tag_source_version', 'description')
    op.add_column('topic_entity_tag_source', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('negated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('validation_value_curation_tools', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source', sa.Column('confidence_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source', sa.Column('validation_value_curator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source', sa.Column('topic_entity_tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('validation_value_author', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('topic_entity_tag_source_topic_entity_tag_id_fkey', 'topic_entity_tag_source', 'topic_entity_tag', ['topic_entity_tag_id'], ['topic_entity_tag_id'], ondelete='CASCADE')
    op.create_unique_constraint('source_topic_entity_tag_unique', 'topic_entity_tag_source', ['topic_entity_tag_id', 'mod_id', 'source'])
    op.create_index('ix_topic_entity_tag_source_topic_entity_tag_id', 'topic_entity_tag_source', ['topic_entity_tag_id'], unique=False)
    op.drop_constraint('topic_entity_tag_source_unique', 'topic_entity_tag_source', type_='unique')
    op.drop_index(op.f('ix_topic_entity_tag_source_source_name'), table_name='topic_entity_tag_source')
    op.drop_column('topic_entity_tag_source', 'source_name')
    op.drop_column('topic_entity_tag_source', 'evidence')
    op.drop_column('topic_entity_tag_source', 'description')
    op.drop_constraint(None, 'topic_entity_tag', type_='foreignkey')
    op.create_index('ix_unique_topic_tag_without_species', 'topic_entity_tag', ['reference_id', 'topic'], unique=True)
    op.create_index('ix_unique_topic_tag_with_species', 'topic_entity_tag', ['reference_id', 'topic', 'species'], unique=True)
    op.create_index('ix_unique_entity_tag', 'topic_entity_tag', ['reference_id', 'topic', 'entity_type', 'entity', 'entity_source', 'species'], unique=True)
    op.drop_index(op.f('ix_topic_entity_tag_topic_entity_tag_source_id'), table_name='topic_entity_tag')
    op.drop_column('topic_entity_tag', 'topic_entity_tag_source_id')
    op.drop_column('topic_entity_tag', 'note')
    op.drop_column('topic_entity_tag', 'negated')
    op.drop_column('topic_entity_tag', 'confidence_level')
    op.drop_table('topic_entity_tag_validation')
    # ### end Alembic commands ###
