"""add_taxon_ids_col_to_mod

Revision ID: 58f23aa35fd2
Revises: a93d99d26cb0
Create Date: 2023-12-19 01:25:13.486499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f23aa35fd2'
down_revision = 'a93d99d26cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add the column as nullable
    op.add_column('mod', sa.Column('taxon_ids', sa.ARRAY(sa.String()), nullable=True))

    # additional columns for version table
    op.add_column('mod_version', sa.Column('taxon_ids', sa.ARRAY(sa.String()), autoincrement=False, nullable=True))
    op.add_column('mod_version', sa.Column('taxon_ids_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # populate the column
    taxon_id_mapping = {
        'ZFIN': ['NCBITaxon:7955'],
        'FB': ['NCBITaxon:7227'],
        'WB': ['NCBITaxon:6239'],
        'RGD': ['NCBITaxon:10116'],
        'MGI': ['NCBITaxon:10090'],
        'SGD': ['NCBITaxon:559292'],
        'XB': ['NCBITaxon:8355', 'NCBITaxon:8364']
    }

    conn = op.get_bind()
    for mod_abbreviation, taxon_ids in taxon_id_mapping.items():
        conn.execute(
            sa.text(
                "UPDATE mod SET taxon_ids = :taxon_ids WHERE abbreviation = :abbreviation"
            ).bindparams(taxon_ids=taxon_ids, abbreviation=mod_abbreviation)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_version', 'taxon_ids_mod')
    op.drop_column('mod_version', 'taxon_ids')
    op.drop_column('mod', 'taxon_ids')
    # ### end Alembic commands ###
