"""ondelete_on_tag_validation

Revision ID: 3be7348a9e68
Revises: fa6db70cdfe7
Create Date: 2023-08-17 17:30:28.641437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be7348a9e68'
down_revision = 'fa6db70cdfe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topic_entity_tag_validation_validating_topic_entity_tag_id_fkey', 'topic_entity_tag_validation', type_='foreignkey')
    op.drop_constraint('topic_entity_tag_validation_validated_topic_entity_tag_id_fkey', 'topic_entity_tag_validation', type_='foreignkey')
    op.create_foreign_key(None, 'topic_entity_tag_validation', 'topic_entity_tag', ['validating_topic_entity_tag_id'], ['topic_entity_tag_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_entity_tag_validation', 'topic_entity_tag', ['validated_topic_entity_tag_id'], ['topic_entity_tag_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_entity_tag_validation', type_='foreignkey')
    op.drop_constraint(None, 'topic_entity_tag_validation', type_='foreignkey')
    op.create_foreign_key('topic_entity_tag_validation_validated_topic_entity_tag_id_fkey', 'topic_entity_tag_validation', 'topic_entity_tag', ['validated_topic_entity_tag_id'], ['topic_entity_tag_id'])
    op.create_foreign_key('topic_entity_tag_validation_validating_topic_entity_tag_id_fkey', 'topic_entity_tag_validation', 'topic_entity_tag', ['validating_topic_entity_tag_id'], ['topic_entity_tag_id'])
    # ### end Alembic commands ###
