"""refractor relation_relation

Revision ID: a93d99d26cb0
Revises: 7f029313b097
Create Date: 2023-12-05 22:51:45.038363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a93d99d26cb0'
down_revision = '7f029313b097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_relation_version',
    sa.Column('reference_relation_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('reference_id_from', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reference_id_to', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reference_relation_type', sa.Enum('RetractionOf', 'CommentOn', 'ErratumFor', 'ReprintOf', 'UpdateOf', 'ExpressionOfConcernFor', 'RepublishedFrom', 'ChapterIn', name='referencerelationtype'), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('reference_id_from_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reference_id_to_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reference_relation_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('reference_relation_id', 'transaction_id')
    )
    op.create_index(op.f('ix_reference_relation_version_end_transaction_id'), 'reference_relation_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_reference_relation_version_operation_type'), 'reference_relation_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_reference_relation_version_reference_id_from'), 'reference_relation_version', ['reference_id_from'], unique=False)
    op.create_index(op.f('ix_reference_relation_version_reference_id_to'), 'reference_relation_version', ['reference_id_to'], unique=False)
    op.create_index(op.f('ix_reference_relation_version_transaction_id'), 'reference_relation_version', ['transaction_id'], unique=False)
    op.create_table('reference_relation',
    sa.Column('reference_relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_id_from', sa.Integer(), nullable=False),
    sa.Column('reference_id_to', sa.Integer(), nullable=False),
    sa.Column('reference_relation_type', sa.Enum('RetractionOf', 'CommentOn', 'ErratumFor', 'ReprintOf', 'UpdateOf', 'ExpressionOfConcernFor', 'RepublishedFrom', 'ChapterIn', name='referencerelationtype'), nullable=False),
    sa.ForeignKeyConstraint(['reference_id_from'], ['reference.reference_id'], ),
    sa.ForeignKeyConstraint(['reference_id_to'], ['reference.reference_id'], ),
    sa.PrimaryKeyConstraint('reference_relation_id'),
    sa.UniqueConstraint('reference_id_from', 'reference_id_to', 'reference_relation_type', name='rc_uniq')
    )
    op.create_index(op.f('ix_reference_relation_reference_id_from'), 'reference_relation', ['reference_id_from'], unique=False)
    op.create_index(op.f('ix_reference_relation_reference_id_to'), 'reference_relation', ['reference_id_to'], unique=False)
    op.drop_index('ix_reference_comments_and_corrections_reference_id_from', table_name='reference_comments_and_corrections')
    op.drop_index('ix_reference_comments_and_corrections_reference_id_to', table_name='reference_comments_and_corrections')
    op.drop_table('reference_comments_and_corrections')
    op.drop_index('ix_reference_comments_and_corrections_version_end_trans_c6e0', table_name='reference_comments_and_corrections_version')
    op.drop_index('ix_reference_comments_and_corrections_version_operation_type', table_name='reference_comments_and_corrections_version')
    op.drop_index('ix_reference_comments_and_corrections_version_reference_id_from', table_name='reference_comments_and_corrections_version')
    op.drop_index('ix_reference_comments_and_corrections_version_reference_id_to', table_name='reference_comments_and_corrections_version')
    op.drop_index('ix_reference_comments_and_corrections_version_transaction_id', table_name='reference_comments_and_corrections_version')
    op.drop_table('reference_comments_and_corrections_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_comments_and_corrections_version',
    sa.Column('reference_comment_and_correction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_id_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_comment_and_correction_type', postgresql.ENUM('RetractionOf', 'CommentOn', 'ErratumFor', 'ReprintOf', 'UpdateOf', 'ExpressionOfConcernFor', 'RepublishedFrom', name='referencecommentandcorrectiontype'), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reference_id_from_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reference_id_to_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reference_comment_and_correction_type_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('reference_comment_and_correction_id', 'transaction_id', name='reference_comments_and_corrections_version_pkey')
    )
    op.create_index('ix_reference_comments_and_corrections_version_transaction_id', 'reference_comments_and_corrections_version', ['transaction_id'], unique=False)
    op.create_index('ix_reference_comments_and_corrections_version_reference_id_to', 'reference_comments_and_corrections_version', ['reference_id_to'], unique=False)
    op.create_index('ix_reference_comments_and_corrections_version_reference_id_from', 'reference_comments_and_corrections_version', ['reference_id_from'], unique=False)
    op.create_index('ix_reference_comments_and_corrections_version_operation_type', 'reference_comments_and_corrections_version', ['operation_type'], unique=False)
    op.create_index('ix_reference_comments_and_corrections_version_end_trans_c6e0', 'reference_comments_and_corrections_version', ['end_transaction_id'], unique=False)
    op.create_table('reference_comments_and_corrections',
    sa.Column('reference_comment_and_correction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reference_id_from', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_comment_and_correction_type', postgresql.ENUM('RetractionOf', 'CommentOn', 'ErratumFor', 'ReprintOf', 'UpdateOf', 'ExpressionOfConcernFor', 'RepublishedFrom', name='referencecommentandcorrectiontype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reference_id_from'], ['reference.reference_id'], name='reference_comments_and_corrections_reference_id_from_fkey'),
    sa.ForeignKeyConstraint(['reference_id_to'], ['reference.reference_id'], name='reference_comments_and_corrections_reference_id_to_fkey'),
    sa.PrimaryKeyConstraint('reference_comment_and_correction_id', name='reference_comments_and_corrections_pkey'),
    sa.UniqueConstraint('reference_id_from', 'reference_id_to', 'reference_comment_and_correction_type', name='rccm_uniq')
    )
    op.create_index('ix_reference_comments_and_corrections_reference_id_to', 'reference_comments_and_corrections', ['reference_id_to'], unique=False)
    op.create_index('ix_reference_comments_and_corrections_reference_id_from', 'reference_comments_and_corrections', ['reference_id_from'], unique=False)
    op.drop_index(op.f('ix_reference_relation_reference_id_to'), table_name='reference_relation')
    op.drop_index(op.f('ix_reference_relation_reference_id_from'), table_name='reference_relation')
    op.drop_table('reference_relation')
    op.drop_index(op.f('ix_reference_relation_version_transaction_id'), table_name='reference_relation_version')
    op.drop_index(op.f('ix_reference_relation_version_reference_id_to'), table_name='reference_relation_version')
    op.drop_index(op.f('ix_reference_relation_version_reference_id_from'), table_name='reference_relation_version')
    op.drop_index(op.f('ix_reference_relation_version_operation_type'), table_name='reference_relation_version')
    op.drop_index(op.f('ix_reference_relation_version_end_transaction_id'), table_name='reference_relation_version')
    op.drop_table('reference_relation_version')
    # ### end Alembic commands ###
