"""updated tet source model

Revision ID: e6209ba4594a
Revises: 7db22549130a
Create Date: 2024-03-06 20:35:46.413428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6209ba4594a'
down_revision = '7db22549130a'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM topic_entity_tag_source"))
    conn.execute(sa.text("DELETE FROM topic_entity_tag_source_version"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_entity_tag_source', sa.Column('data_provider_id', sa.Integer(), nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('secondary_data_provider_id', sa.Integer(), nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('source_evidence_assertion', sa.String(), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_source_data_provider_id'), 'topic_entity_tag_source', ['data_provider_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_secondary_data_provider_id'), 'topic_entity_tag_source', ['secondary_data_provider_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_source_evidence_assertion'), 'topic_entity_tag_source', ['source_evidence_assertion'], unique=False)
    op.drop_constraint('topic_entity_tag_source_unique', 'topic_entity_tag_source', type_='unique')
    op.create_unique_constraint('topic_entity_tag_source_unique', 'topic_entity_tag_source', ['source_evidence_assertion', 'source_method', 'data_provider_id', 'secondary_data_provider_id'])
    op.drop_index('ix_topic_entity_tag_source_mod_id', table_name='topic_entity_tag_source')
    op.drop_index('ix_topic_entity_tag_source_source_type', table_name='topic_entity_tag_source')
    op.drop_constraint('topic_entity_tag_source_mod_id_fkey', 'topic_entity_tag_source', type_='foreignkey')
    op.create_foreign_key(None, 'topic_entity_tag_source', 'mod', ['secondary_data_provider_id'], ['mod_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_entity_tag_source', 'mod', ['data_provider_id'], ['mod_id'], ondelete='CASCADE')
    op.drop_column('topic_entity_tag_source', 'evidence')
    op.drop_column('topic_entity_tag_source', 'mod_id')
    op.drop_column('topic_entity_tag_source', 'source_type')
    op.add_column('topic_entity_tag_source_version', sa.Column('data_provider_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('data_provider_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('secondary_data_provider_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('secondary_data_provider_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('source_evidence_assertion', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('source_evidence_assertion_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_source_version_data_provider_id'), 'topic_entity_tag_source_version', ['data_provider_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_version_secondary_data_provider_id'), 'topic_entity_tag_source_version', ['secondary_data_provider_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_source_version_source_evidence_assertion'), 'topic_entity_tag_source_version', ['source_evidence_assertion'], unique=False)
    op.drop_index('ix_topic_entity_tag_source_version_mod_id', table_name='topic_entity_tag_source_version')
    op.drop_index('ix_topic_entity_tag_source_version_source_type', table_name='topic_entity_tag_source_version')
    op.drop_column('topic_entity_tag_source_version', 'evidence')
    op.drop_column('topic_entity_tag_source_version', 'mod_id')
    op.drop_column('topic_entity_tag_source_version', 'mod_id_mod')
    op.drop_column('topic_entity_tag_source_version', 'source_type_mod')
    op.drop_column('topic_entity_tag_source_version', 'source_type')
    op.drop_column('topic_entity_tag_source_version', 'evidence_mod')
    # ### end Alembic commands ###
   

def downgrade():
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM topic_entity_tag_source"))
    conn.execute(sa.text("DELETE FROM topic_entity_tag_source_version"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_entity_tag_source_version', sa.Column('evidence_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('source_type_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('mod_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source_version', sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_source_version', sa.Column('evidence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_topic_entity_tag_source_version_source_type', 'topic_entity_tag_source_version', ['source_type'], unique=False)
    op.create_index('ix_topic_entity_tag_source_version_mod_id', 'topic_entity_tag_source_version', ['mod_id'], unique=False)
    op.drop_index(op.f('ix_topic_entity_tag_source_version_source_evidence_assertion'), table_name='topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_secondary_data_provider_id'), table_name='topic_entity_tag_source_version')
    op.drop_index(op.f('ix_topic_entity_tag_source_version_data_provider_id'), table_name='topic_entity_tag_source_version')
    op.drop_column('topic_entity_tag_source_version', 'source_evidence_assertion_mod')
    op.drop_column('topic_entity_tag_source_version', 'source_evidence_assertion')
    op.drop_column('topic_entity_tag_source_version', 'secondary_data_provider_id_mod')
    op.drop_column('topic_entity_tag_source_version', 'secondary_data_provider_id')
    op.drop_column('topic_entity_tag_source_version', 'data_provider_id_mod')
    op.drop_column('topic_entity_tag_source_version', 'data_provider_id')
    op.add_column('topic_entity_tag_source', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('topic_entity_tag_source', sa.Column('evidence', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'topic_entity_tag_source', type_='foreignkey')
    op.drop_constraint(None, 'topic_entity_tag_source', type_='foreignkey')
    op.create_foreign_key('topic_entity_tag_source_mod_id_fkey', 'topic_entity_tag_source', 'mod', ['mod_id'], ['mod_id'], ondelete='CASCADE')
    op.create_index('ix_topic_entity_tag_source_source_type', 'topic_entity_tag_source', ['source_type'], unique=False)
    op.create_index('ix_topic_entity_tag_source_mod_id', 'topic_entity_tag_source', ['mod_id'], unique=False)
    op.drop_constraint('topic_entity_tag_source_unique', 'topic_entity_tag_source', type_='unique')
    op.create_unique_constraint('topic_entity_tag_source_unique', 'topic_entity_tag_source', ['source_type', 'source_method', 'mod_id'])
    op.drop_index(op.f('ix_topic_entity_tag_source_source_evidence_assertion'), table_name='topic_entity_tag_source')
    op.drop_index(op.f('ix_topic_entity_tag_source_secondary_data_provider_id'), table_name='topic_entity_tag_source')
    op.drop_index(op.f('ix_topic_entity_tag_source_data_provider_id'), table_name='topic_entity_tag_source')
    op.drop_column('topic_entity_tag_source', 'source_evidence_assertion')
    op.drop_column('topic_entity_tag_source', 'secondary_data_provider_id')
    op.drop_column('topic_entity_tag_source', 'data_provider_id')
    # ### end Alembic commands ###
