"""added workflow_transition_table

Revision ID: 6755b395f397
Revises: 77a7fd5a96a7
Create Date: 2024-06-13 16:01:11.470456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6755b395f397'
down_revision = '77a7fd5a96a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_transition_version',
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('workflow_transition_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transition_from', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transition_to', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mod_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('transition_from_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('transition_to_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_transition_id', 'transaction_id')
    )
    op.create_index(op.f('ix_workflow_transition_version_date_created'), 'workflow_transition_version', ['date_created'], unique=False)
    op.create_index(op.f('ix_workflow_transition_version_date_updated'), 'workflow_transition_version', ['date_updated'], unique=False)
    op.create_index(op.f('ix_workflow_transition_version_end_transaction_id'), 'workflow_transition_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_workflow_transition_version_mod_id'), 'workflow_transition_version', ['mod_id'], unique=False)
    op.create_index(op.f('ix_workflow_transition_version_operation_type'), 'workflow_transition_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_workflow_transition_version_transaction_id'), 'workflow_transition_version', ['transaction_id'], unique=False)
    op.create_table('workflow_transition',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('workflow_transition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('transition_from', sa.String(), nullable=False),
    sa.Column('transition_to', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('workflow_transition_id')
    )
    op.create_index(op.f('ix_workflow_transition_date_created'), 'workflow_transition', ['date_created'], unique=False)
    op.create_index(op.f('ix_workflow_transition_date_updated'), 'workflow_transition', ['date_updated'], unique=False)
    op.create_index(op.f('ix_workflow_transition_mod_id'), 'workflow_transition', ['mod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_transition_mod_id'), table_name='workflow_transition')
    op.drop_index(op.f('ix_workflow_transition_date_updated'), table_name='workflow_transition')
    op.drop_index(op.f('ix_workflow_transition_date_created'), table_name='workflow_transition')
    op.drop_table('workflow_transition')
    op.drop_index(op.f('ix_workflow_transition_version_transaction_id'), table_name='workflow_transition_version')
    op.drop_index(op.f('ix_workflow_transition_version_operation_type'), table_name='workflow_transition_version')
    op.drop_index(op.f('ix_workflow_transition_version_mod_id'), table_name='workflow_transition_version')
    op.drop_index(op.f('ix_workflow_transition_version_end_transaction_id'), table_name='workflow_transition_version')
    op.drop_index(op.f('ix_workflow_transition_version_date_updated'), table_name='workflow_transition_version')
    op.drop_index(op.f('ix_workflow_transition_version_date_created'), table_name='workflow_transition_version')
    op.drop_table('workflow_transition_version')
    # ### end Alembic commands ###
