"""backward relation constraint

Revision ID: a2f2d30caead
Revises: fbbe8c1474e7
Create Date: 2024-01-25 18:28:52.817952

"""
from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f2d30caead'
down_revision = 'fbbe8c1474e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rc_uniq', 'reference_relation', type_='unique')
    op.execute('CREATE UNIQUE INDEX ix_reference_relation_least_greatest ON public.reference_relation USING btree (LEAST(reference_id_from, reference_id_to) ASC NULLS LAST, GREATEST(reference_id_from, reference_id_to) ASC NULLS LAST)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rc_uniq', 'reference_relation', ['reference_id_from', 'reference_id_to'])
    op.drop_index('ix_reference_relation_least_greatest', table_name='reference_relation')
    # ### end Alembic commands ###
