"""remove mod_taxon

Revision ID: 77a7fd5a96a7
Revises: 5352874e222d
Create Date: 2024-03-18 10:57:19.352723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77a7fd5a96a7'
down_revision = '5352874e222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mod_taxon_version_date_created', table_name='mod_taxon_version')
    op.drop_index('ix_mod_taxon_version_date_updated', table_name='mod_taxon_version')
    op.drop_index('ix_mod_taxon_version_end_transaction_id', table_name='mod_taxon_version')
    op.drop_index('ix_mod_taxon_version_mod_id', table_name='mod_taxon_version')
    op.drop_index('ix_mod_taxon_version_operation_type', table_name='mod_taxon_version')
    op.drop_index('ix_mod_taxon_version_transaction_id', table_name='mod_taxon_version')
    op.drop_table('mod_taxon_version')
    op.drop_index('ix_mod_taxon_date_created', table_name='mod_taxon')
    op.drop_index('ix_mod_taxon_date_updated', table_name='mod_taxon')
    op.drop_index('ix_mod_taxon_mod_id', table_name='mod_taxon')
    op.drop_table('mod_taxon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_taxon',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mod_taxon_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taxon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='mod_taxon_created_by_fkey'),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], name='mod_taxon_mod_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='mod_taxon_updated_by_fkey'),
    sa.PrimaryKeyConstraint('mod_taxon_id', name='mod_taxon_pkey'),
    sa.UniqueConstraint('taxon', name='mod_taxon_taxon_key')
    )
    op.create_index('ix_mod_taxon_mod_id', 'mod_taxon', ['mod_id'], unique=False)
    op.create_index('ix_mod_taxon_date_updated', 'mod_taxon', ['date_updated'], unique=False)
    op.create_index('ix_mod_taxon_date_created', 'mod_taxon', ['date_created'], unique=False)
    op.create_table('mod_taxon_version',
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mod_taxon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taxon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('date_created_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_updated_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mod_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('taxon_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('mod_taxon_id', 'transaction_id', name='mod_taxon_version_pkey')
    )
    op.create_index('ix_mod_taxon_version_transaction_id', 'mod_taxon_version', ['transaction_id'], unique=False)
    op.create_index('ix_mod_taxon_version_operation_type', 'mod_taxon_version', ['operation_type'], unique=False)
    op.create_index('ix_mod_taxon_version_mod_id', 'mod_taxon_version', ['mod_id'], unique=False)
    op.create_index('ix_mod_taxon_version_end_transaction_id', 'mod_taxon_version', ['end_transaction_id'], unique=False)
    op.create_index('ix_mod_taxon_version_date_updated', 'mod_taxon_version', ['date_updated'], unique=False)
    op.create_index('ix_mod_taxon_version_date_created', 'mod_taxon_version', ['date_created'], unique=False)
    # ### end Alembic commands ###
