"""now add the data


Revision ID: 6230dc3aee08
Revises: 70945a51c994
Create Date: 2024-07-08 16:34:24.081366

"""
from alembic import op
import sqlalchemy as sa
from agr_literature_service.api.crud.topic_entity_tag_crud import revalidate_all_tags

# revision identifiers, used by Alembic.
revision = '6230dc3aee08'
down_revision = '70945a51c994'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    revalidate_all_tags()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
