"""reference_relations_from_to_constraint

Revision ID: 88ccd65195a1
Revises: e9f8f928e631
Create Date: 2024-01-17 00:16:07.957932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ccd65195a1'
down_revision = 'e9f8f928e631'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "DELETE FROM reference_relation WHERE reference_relation_id = 6628"
        )
    )
    conn.execute(
        sa.text(
            "DELETE FROM reference_relation_version WHERE reference_relation_id = 6628"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rc_uniq', 'reference_relation', type_='unique')
    op.create_unique_constraint('rc_uniq', 'reference_relation', ['reference_id_from', 'reference_id_to'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rc_uniq', 'reference_relation', type_='unique')
    op.create_unique_constraint('rc_uniq', 'reference_relation', ['reference_id_from', 'reference_id_to', 'reference_relation_type'])
    # ### end Alembic commands ###
