"""reference relation from not to

Revision ID: 7db22549130a
Revises: ae59140a86a6
Create Date: 2024-02-27 09:12:04.460531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db22549130a'
down_revision = 'ae59140a86a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'reference_relation_from_not_to',
        'reference_relation',
        '(reference_id_from != reference_id_to)'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reference_relation_from_not_to', 'reference_relation', type_='check')
    # ### end Alembic commands ###
