"""validation unique

Revision ID: 8e9d88108979
Revises: a2f2d30caead
Create Date: 2024-01-31 17:10:52.627475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9d88108979'
down_revision = 'a2f2d30caead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('validation_unique', 'topic_entity_tag_validation', ['validated_topic_entity_tag_id', 'validating_topic_entity_tag_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('validation_unique', 'topic_entity_tag_validation', type_='unique')
    # ### end Alembic commands ###
