"""tet_entity_type_only_with_entity

Revision ID: ae59140a86a6
Revises: 8e9d88108979
Create Date: 2024-02-05 09:21:25.483907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae59140a86a6'
down_revision = '8e9d88108979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valid_entity_type_dependencies', 'topic_entity_tag', type_='check')

    # Add the new check constraint
    op.create_check_constraint(
        'valid_entity_type_dependencies',
        'topic_entity_tag',
        sa.sql.text("""
                (
                    (entity_type IS NOT NULL AND entity IS NOT NULL AND entity_source IS NOT NULL AND species IS NOT NULL)
                    OR
                    (entity_type IS NULL AND entity IS NULL AND entity_source IS NULL)
                )
            """)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valid_entity_type_dependencies', 'topic_entity_tag', type_='check')

    # Add the new check constraint
    op.create_check_constraint(
        'valid_entity_type_dependencies',
        'topic_entity_tag',
        sa.sql.text("""
                (
                    (entity_type IS NOT NULL AND entity IS NOT NULL AND entity_source IS NOT NULL AND species IS NOT NULL AND topic != 'ATP:0000123' AND entity_type != 'ATP:0000123')
                    OR
                    (topic = 'ATP:0000123' AND entity_type = 'ATP:0000123' AND entity_source IS NOT NULL AND species IS NULL)
                    OR
                    (entity_type IS NULL AND entity IS NULL AND entity_source IS NULL)
                    OR
                    (entity_type IS NOT NULL AND entity IS NULL AND entity_source IS NULL AND species IS NOT NULL AND negated IS TRUE)
                )
            """)
    )
    # ### end Alembic commands ###
