"""add model_id to TET

Revision ID: 4e4880f20f0d
Revises: 7b3a2f9c1d2e
Create Date: 2025-09-04 15:32:30.363278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e4880f20f0d'
down_revision = '7b3a2f9c1d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_indexing_priority_version_end_transaction_id', table_name='indexing_priority_version')
    op.drop_index('ix_indexing_priority_version_operation_type', table_name='indexing_priority_version')
    op.drop_index('ix_indexing_priority_version_transaction_id', table_name='indexing_priority_version')
    op.drop_table('indexing_priority_version')
    op.create_index(op.f('ix_indexing_priority_date_created'), 'indexing_priority', ['date_created'], unique=False)
    op.create_index(op.f('ix_indexing_priority_date_updated'), 'indexing_priority', ['date_updated'], unique=False)
    op.add_column('topic_entity_tag', sa.Column('ml_model_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_topic_entity_tag_ml_model_id'), 'topic_entity_tag', ['ml_model_id'], unique=False)
    op.create_foreign_key(None, 'topic_entity_tag', 'ml_model', ['ml_model_id'], ['ml_model_id'])
    op.add_column('topic_entity_tag_version', sa.Column('ml_model_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('ml_model_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_topic_entity_tag_version_ml_model_id'), 'topic_entity_tag_version', ['ml_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_entity_tag_version_ml_model_id'), table_name='topic_entity_tag_version')
    op.drop_column('topic_entity_tag_version', 'ml_model_id_mod')
    op.drop_column('topic_entity_tag_version', 'ml_model_id')
    op.drop_constraint(None, 'topic_entity_tag', type_='foreignkey')
    op.drop_index(op.f('ix_topic_entity_tag_ml_model_id'), table_name='topic_entity_tag')
    op.drop_column('topic_entity_tag', 'ml_model_id')
    op.drop_index(op.f('ix_indexing_priority_date_updated'), table_name='indexing_priority')
    op.drop_index(op.f('ix_indexing_priority_date_created'), table_name='indexing_priority')
    op.create_table('indexing_priority_version',
    sa.Column('indexing_priority_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indexing_priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validation_by_biocurator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('indexing_priority_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reference_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mod_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('confidence_score_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('validation_by_biocurator_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_created_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_updated_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_by_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('indexing_priority_id', 'transaction_id', name='indexing_priority_version_pkey')
    )
    op.create_index('ix_indexing_priority_version_transaction_id', 'indexing_priority_version', ['transaction_id'], unique=False)
    op.create_index('ix_indexing_priority_version_operation_type', 'indexing_priority_version', ['operation_type'], unique=False)
    op.create_index('ix_indexing_priority_version_end_transaction_id', 'indexing_priority_version', ['end_transaction_id'], unique=False)
    # ### end Alembic commands ###
