"""new data novelty column

Revision ID: 7e1c9c466d97
Revises: dd49adbeca49
Create Date: 2025-07-08 16:24:25.033786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1c9c466d97'
down_revision = 'dd49adbeca49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_entity_tag', sa.Column('data_novelty', sa.String(), nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('data_novelty', sa.String(), autoincrement=False, nullable=True))
    op.add_column('topic_entity_tag_version', sa.Column('data_novelty_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_entity_tag_version', 'data_novelty_mod')
    op.drop_column('topic_entity_tag_version', 'data_novelty')
    op.drop_column('topic_entity_tag', 'data_novelty')
    # ### end Alembic commands ###
