"""add_ml_model_id_to_topic_entity_tag

Revision ID: 5ed317af426f
Revises: abc123def456
Create Date: 2025-09-18 14:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed317af426f'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_entity_tag', sa.Column('ml_model_id', sa.Integer(), nullable=True))
    op.create_index('ix_topic_entity_tag_ml_model_id', 'topic_entity_tag', ['ml_model_id'], unique=False)
    op.create_foreign_key('fk_topic_entity_tag_ml_model', 'topic_entity_tag', 'ml_model', ['ml_model_id'], ['ml_model_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_topic_entity_tag_ml_model', 'topic_entity_tag', type_='foreignkey')
    op.drop_index('ix_topic_entity_tag_ml_model_id', table_name='topic_entity_tag')
    op.drop_column('topic_entity_tag', 'ml_model_id')
    # ### end Alembic commands ###