"""Add unique constraint to curation_status table model requiring unique topic + reference_id + mod_id

Revision ID: 19a726040ce5
Revises: a3e751dff3e2
Create Date: 2025-10-22 20:40:09.771813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a726040ce5'
down_revision = 'fff02f4044e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('curation_status_unique', 'curation_status', ['topic', 'reference_id', 'mod_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('curation_status_unique', 'curation_status', type_='unique')
    # ### end Alembic commands ###
