"""workflow_tag_topic addition

Revision ID: bf8c336530f9
Revises: a286f0a59a44
Create Date: 2025-03-07 17:00:28.761932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c336530f9'
down_revision = 'a286f0a59a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_tag_topic',
    sa.Column('workflow_tag_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_tag', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('workflow_tag_topic_id')
    )
    op.create_index(op.f('ix_workflow_tag_topic_date_created'), 'workflow_tag_topic', ['date_created'], unique=False)
    op.create_index(op.f('ix_workflow_tag_topic_date_updated'), 'workflow_tag_topic', ['date_updated'], unique=False)
    op.create_index(op.f('ix_workflow_tag_topic_workflow_tag'), 'workflow_tag_topic', ['workflow_tag'], unique=True)
    # ### end Alembic commands ###

    needed_to_topic = {
        ### Actually we need the "needed" tags and not the "completed" tags ###
        # ATP:0000247	allele phenotype classification complete -> variation phenotype ATP:0000083  (name change will happen to allele phenotype)
        "ATP:0000249": "ATP:0000083",
        # ATP:0000199	antibody classification complete ->antibody ATP:0000096
        "ATP:0000202": "ATP:0000096",
        # ATP:0000168	catalytic activity classification complete -> catalytic activity "ATP:0000061""
        "ATP:0000180": "ATP:0000061",
        # ATP:0000167	disease classification complete -> disease model ATP:0000152
        "ATP:0000179": "ATP:0000152",
        # ATP:0000170	expression classification complete -> gene expression ATP:0000010
        "ATP:0000181": "ATP:0000010",
        # ATP:0000171	genetic interaction classification complete -> genetic interaction ATP:0000068
        "ATP:0000182": "ATP:0000068",
        # ATP:0000244	physical interaction classification complete -> physical interaction ATP:0000069
        "ATP:0000264": "ATP:0000069",
        # ATP:0000245	regulatory interaction classification complete -> ATP:0000070 regulatory interaction
        "ATP:0000263": "ATP:0000070",
        # ATP:0000222	RNAi classification complete  -> ATP:0000082 RNAi phenotype
        "ATP:0000225": "ATP:0000082",
        # ATP:0000248	transgene overexpression phenotype classification complete ->ATP:0000084 overexpression phenotype
        "ATP:0000262": "ATP:0000084",
        # ATP:0000294	transporter activity classification complete ->ATP:0000062 transporter function
        "ATP:0000297": "ATP:0000062",
        # TODO: ATP:0000298 	genetic data classification complete -> ATP:0000207 no genetic data (is a curation tag)
        # TODO: WE HAVE A COMPLETE BUT NO NEEDED
        # ATP:0000290	new allele classification complete -> ATP:0000006 allele AND new data ATP:0000229
        "ATP:0000293": "ATP:0000006", # new classical allele
        # ATP:0000286	new transgenic allele classification complete -> transgenic allele ATP:0000110 & new data ATP:0000229
        "ATP:0000289": "ATP:0000006",  # new transgenic allele
        # ATP:0000303	pre-indexing prioritization complete -> ATP:0000210 indexing priority (is a curation tag)
        "ATP:0000306": "ATP:0000210"
    }
    """
        ATP:0000247	allele phenotype classification complete -> variation phenotype ATP:0000083  (name change will happen to allele phenotype)
ATP:0000199	antibody classification complete ->antibody ATP:0000096
ATP:0000168	catalytic activity classification complete -> catalytic activity ATP:0000061
ATP:0000167	disease classification complete -> disease model ATP:0000152
ATP:0000170	expression classification complete -> gene expression ATP:0000010
ATP:0000171	genetic interaction classification complete -> genetic interaction ATP:0000068
ATP:0000244	physical interaction classification complete -> physical interaction ATP:0000069
ATP:0000245	regulatory interaction classification complete -> ATP:0000070 regulatory interaction
ATP:0000222	RNAi classification complete  -> ATP:0000082 RNAi phenotype
ATP:0000248	transgene overexpression phenotype classification complete ->ATP:0000084 overexpression phenotype
ATP:0000294	transporter activity classification complete ->ATP:0000062 transporter function
ATP:0000298 	genetic data classification complete -> ATP:0000207 no genetic data (is a curation tag)
ATP:0000290	new allele classification complete -> ATP:0000006 allele AND new data ATP:0000229
ATP:0000303	pre-indexing prioritization complete -> ATP:0000210 indexing priority (is a curation tag)
ATP:0000307 	new transgenic construct classification complete ->ATP:0000013 transgenic construct  & new data ATP:0000229
right now this isn't being used
ATP:0000286	new transgenic allele classification complete -> transgenic allele ATP:0000110 & new data ATP:0000229
Workflow tags for curation tag applying pipelines will have a new workflow parent “curation classification” ATP:0000311
ATP:0000303 pre-indexing prioritization complete -> ATP:0000210 indexing priority (is a curation tag)
ATP:0000298 genetic data classification complete -> ATP:0000207 no genetic data (is a curation tag)
"""
    conn = op.get_bind()
    for wf_tag, topic_tag in needed_to_topic.items():
        conn.execute(
            sa.text(
                "INSERT INTO workflow_tag_topic (workflow_tag, topic, date_created) VALUES (:workflow_tag, :topic_tag, NOW())",
            ).bindparams(workflow_tag=wf_tag, topic_tag=topic_tag)
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tag_topic_workflow_tag'), table_name='workflow_tag_topic')
    op.drop_index(op.f('ix_workflow_tag_topic_date_updated'), table_name='workflow_tag_topic')
    op.drop_index(op.f('ix_workflow_tag_topic_date_created'), table_name='workflow_tag_topic')
    op.drop_table('workflow_tag_topic')
    # ### end Alembic commands ###
