"""workflow_tag_topic addition

Revision ID: bf8c336530f9
Revises: a286f0a59a44
Create Date: 2025-03-07 17:00:28.761932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c336530f9'
down_revision = 'a286f0a59a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_tag_topic',
    sa.Column('workflow_tag_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_tag', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('workflow_tag_topic_id')
    )
    op.create_index(op.f('ix_workflow_tag_topic_date_created'), 'workflow_tag_topic', ['date_created'], unique=False)
    op.create_index(op.f('ix_workflow_tag_topic_date_updated'), 'workflow_tag_topic', ['date_updated'], unique=False)
    op.create_index(op.f('ix_workflow_tag_topic_workflow_tag'), 'workflow_tag_topic', ['workflow_tag'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tag_topic_workflow_tag'), table_name='workflow_tag_topic')
    op.drop_index(op.f('ix_workflow_tag_topic_date_updated'), table_name='workflow_tag_topic')
    op.drop_index(op.f('ix_workflow_tag_topic_date_created'), table_name='workflow_tag_topic')
    op.drop_table('workflow_tag_topic')
    # ### end Alembic commands ###
