"""model update

Revision ID: 99071bc88199
Revises: bf8c336530f9
Create Date: 2025-04-04 12:50:53.058766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99071bc88199'
down_revision = 'bf8c336530f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model', sa.Column('species', sa.String(), nullable=True))
    op.add_column('ml_model', sa.Column('production', sa.Boolean(), nullable=True, default=True))
    op.add_column('ml_model', sa.Column('negated', sa.Boolean(), nullable=True, default=True))
    op.add_column('ml_model', sa.Column('novel_topic_data', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_model', 'novel_topic_data')
    op.drop_column('ml_model', 'negated')
    op.drop_column('ml_model', 'production')
    op.drop_column('ml_model', 'species')
    # ### end Alembic commands ###
