"""curation status table

Revision ID: eeaedb350562
Revises: e8d400ec03b2
Create Date: 2025-04-28 10:59:24.747662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaedb350562'
down_revision = 'e8d400ec03b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curation_status',
    sa.Column('curation_status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('curation_status', sa.String(), nullable=True),
    sa.Column('controlled_note', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.reference_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('curation_status_id')
    )
    op.create_index(op.f('ix_curation_status_date_created'), 'curation_status', ['date_created'], unique=False)
    op.create_index(op.f('ix_curation_status_date_updated'), 'curation_status', ['date_updated'], unique=False)
    op.create_index(op.f('ix_curation_status_mod_id'), 'curation_status', ['mod_id'], unique=False)
    op.create_index(op.f('ix_curation_status_reference_id'), 'curation_status', ['reference_id'], unique=False)
    op.create_index(op.f('ix_curation_status_topic'), 'curation_status', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curation_status_topic'), table_name='curation_status')
    op.drop_index(op.f('ix_curation_status_reference_id'), table_name='curation_status')
    op.drop_index(op.f('ix_curation_status_mod_id'), table_name='curation_status')
    op.drop_index(op.f('ix_curation_status_date_updated'), table_name='curation_status')
    op.drop_index(op.f('ix_curation_status_date_created'), table_name='curation_status')
    op.drop_table('curation_status')
    # ### end Alembic commands ###
