"""new ML model table

Revision ID: 46f75491c453
Revises: 8f29ec3495f1
Create Date: 2025-01-24 02:17:05.744256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f75491c453'
down_revision = '8f29ec3495f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('ml_model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.dataset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ml_model_id'),
    sa.UniqueConstraint('task_type', 'mod_id', 'topic', 'version_num', name='uq_ml_model_task_mod_topic_version')
    )
    op.create_index(op.f('ix_ml_model_dataset_id'), 'ml_model', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_model_mod_id'), 'ml_model', ['mod_id'], unique=False)
    op.create_index(op.f('ix_ml_model_model_type'), 'ml_model', ['model_type'], unique=False)
    op.create_index(op.f('ix_ml_model_task_type'), 'ml_model', ['task_type'], unique=False)
    op.create_index(op.f('ix_ml_model_topic'), 'ml_model', ['topic'], unique=False)
    op.create_index(op.f('ix_ml_model_version_num'), 'ml_model', ['version_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_model_version_num'), table_name='ml_model')
    op.drop_index(op.f('ix_ml_model_topic'), table_name='ml_model')
    op.drop_index(op.f('ix_ml_model_task_type'), table_name='ml_model')
    op.drop_index(op.f('ix_ml_model_model_type'), table_name='ml_model')
    op.drop_index(op.f('ix_ml_model_mod_id'), table_name='ml_model')
    op.drop_index(op.f('ix_ml_model_dataset_id'), table_name='ml_model')
    op.drop_table('ml_model')
    # ### end Alembic commands ###
