"""tag source rename and curation status source associations

Revision ID: dca4009ee029
Revises: a7c3e5d91f26
Create Date: 2026-09-16 18:06:42.990217

SCRUM-6518, in one revision:

1. topic_entity_tag_source -> tag_source. The source table is now shared by
   topic entity tags and curation status entries, so it loses the
   topic_entity_tag prefix.
2. curation_status_source_association: one row per (curation_status,
   tag_source) holding what THAT source reported. Independent of the base row -
   values may disagree and nothing is reconciled.
3. Version tables for the association and for curation_status, which had no
   history at all.
4. Every existing curation_status row is stamped with its per-MOD ABC source.
5. Saved AgGrid layouts in person_setting.json_settings are rewritten, so the
   column rename does not orphan curators' persisted tet_table preferences.
6. tag_source.validation_type 'professional_curator' is normalised to
   'professional_biocurator'. Validation edges are computed from
   ATP_ID_SOURCE_CURATOR ('professional_biocurator'), so a source carrying the
   old value would never have had its curator validations counted. No row in
   dev or prod currently has it - every ABC source is already
   'professional_biocurator' - so this is a no-op there. It is here to catch
   stage, and any row the old CURATOR_VALIDATION_TYPE constant may create
   between now and deploy (AGR has curation_status rows but no ABC source yet,
   so it is the likely candidate).

This file was autogenerated and then edited. Two classes of change were removed
from the generated output:

a) The RENAME. Alembic cannot see a rename and rendered it as DROP TABLE
   topic_entity_tag_source + CREATE TABLE tag_source, plus a drop/add of the FK
   column on topic_entity_tag. Applied as generated against dev that would have
   destroyed 73 source rows and blanked the source link on 3,496,920
   topic_entity_tag rows. It is ALTER ... RENAME here instead, which preserves
   the data, the FK and the sequence. Verified on a copy of dev: upgrade and
   downgrade both round-trip with all 32 identifiers and all row counts intact.

b) Pre-existing model/database drift unrelated to this ticket:
   user_id_migration_backup, laboratory_person_version.lab_position_mod,
   person_lineage*_version.relationship_mod, uq_person_curie, uq_users_user_id,
   uq_image_permission_name and the users.id / users.user_id type changes.
   Those need their own ticket; this revision does not touch them.

The three create_table blocks below are the generated output verbatim - the
_mod column sets come from continuum's PropertyModTrackerPlugin, so the
generator is authoritative for them.

Two of the version-table index names are 64 characters, one over PostgreSQL's
63-char identifier limit:
    ix_curation_status_source_association_version_curation_status_id
    ix_curation_status_source_association_version_end_transaction_id
op.f() wraps them in a conv() truncated label, so SQLAlchemy truncates with a
hash suffix rather than raising, and the indexes land as
..._curation__c56e / ..._end_trans_5a32. This is deliberate rather than fixed:
alembic compares post-truncation names, so autogenerate stays clean, whereas
renaming them explicitly here would introduce permanent drift. Anyone dropping
or referencing these indexes by name must use the truncated form.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dca4009ee029'
down_revision = 'a7c3e5d91f26'
branch_labels = None
depends_on = None

OLD = "topic_entity_tag_source"
NEW = "tag_source"

# (table, old column, new column). Renamed before the tables themselves, so on
# upgrade these are the pre-rename table names.
COLUMN_RENAMES = [
    ("topic_entity_tag_source", "topic_entity_tag_source_id", "tag_source_id"),
    ("topic_entity_tag_source_version", "topic_entity_tag_source_id", "tag_source_id"),
    ("topic_entity_tag", "topic_entity_tag_source_id", "tag_source_id"),
    ("topic_entity_tag_version", "topic_entity_tag_source_id", "tag_source_id"),
    ("topic_entity_tag_version", "topic_entity_tag_source_id_mod", "tag_source_id_mod"),
]

# The per-MOD ABC source, matching get_or_create_abc_source in tag_source_crud.
ABC_ASSERTION = "ATP:0000036"
ABC_METHOD = "abc_literature_system"
ABC_VALIDATION_TYPE = "professional_biocurator"
ABC_DESCRIPTION = ("Trained professional biocurator specializing in curation of model organism "
                   "data using the ABC data entry form.")


def _rename_identifiers(old: str, new: str) -> None:
    """Rename every constraint, index and sequence whose name embeds ``old``.

    Constraints run first so a PK/UNIQUE rename also carries its backing index.
    NOTE this does NOT guarantee the index loop skips them. Prod's names are
    doubled - topic_entity_topic_entity_tag_source_pkey - so one pass yields
    topic_entity_tag_source_pkey, which still matches the pattern and is
    renamed again by the index loop, landing on tag_source_pkey. That second
    pass is correct and verified against a replica built from prod's real
    identifier names; do not "simplify" either loop on the assumption that one
    pass is always enough.

    Renaming by pattern rather than by literal name is what lets the revision
    handle dev and prod carrying different names for the same objects.
    """
    op.execute(f"""
        DO $$
        DECLARE r record;
        BEGIN
            FOR r IN SELECT con.conname AS name, con.conrelid::regclass::text AS tbl
                       FROM pg_constraint con
                       JOIN pg_namespace n ON n.oid = con.connamespace
                      WHERE n.nspname = 'public'
                        AND con.conname LIKE '%{old}%'
            LOOP
                EXECUTE format('ALTER TABLE %s RENAME CONSTRAINT %I TO %I',
                               r.tbl, r.name, replace(r.name, '{old}', '{new}'));
            END LOOP;

            FOR r IN SELECT c.relname AS name
                       FROM pg_class c
                       JOIN pg_namespace n ON n.oid = c.relnamespace
                      WHERE n.nspname = 'public' AND c.relkind = 'i'
                        AND c.relname LIKE '%{old}%'
            LOOP
                EXECUTE format('ALTER INDEX %I RENAME TO %I',
                               r.name, replace(r.name, '{old}', '{new}'));
            END LOOP;

            FOR r IN SELECT c.relname AS name
                       FROM pg_class c
                       JOIN pg_namespace n ON n.oid = c.relnamespace
                      WHERE n.nspname = 'public' AND c.relkind = 'S'
                        AND c.relname LIKE '%{old}%'
            LOOP
                EXECUTE format('ALTER SEQUENCE %I RENAME TO %I',
                               r.name, replace(r.name, '{old}', '{new}'));
            END LOOP;
        END $$;
    """)


def _assert_no_identifiers(fragment: str, direction: str) -> None:
    """Fail loudly rather than leave a half-renamed schema."""
    op.execute(f"""
        DO $$
        DECLARE leftover text;
        BEGIN
            SELECT string_agg(name, ', ') INTO leftover FROM (
                SELECT c.relname AS name
                  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                 WHERE n.nspname = 'public' AND c.relkind IN ('r','i','S')
                   AND c.relname LIKE '%{fragment}%'
                UNION ALL
                SELECT con.conname
                  FROM pg_constraint con JOIN pg_namespace n ON n.oid = con.connamespace
                 WHERE n.nspname = 'public' AND con.conname LIKE '%{fragment}%'
                UNION ALL
                SELECT table_name || '.' || column_name
                  FROM information_schema.columns
                 WHERE table_schema = 'public' AND column_name LIKE '{fragment}%'
            ) t;
            IF leftover IS NOT NULL THEN
                RAISE EXCEPTION '{direction} left these % objects behind: %',
                    '{fragment}', leftover;
            END IF;
        END $$;
    """)


def _rename_source_table_to_tag_source() -> None:
    for table, old_column, new_column in COLUMN_RENAMES:
        op.execute(f'ALTER TABLE {table} RENAME COLUMN {old_column} TO {new_column}')
    _rename_identifiers(OLD, NEW)
    op.execute(f'ALTER TABLE {OLD} RENAME TO {NEW}')
    op.execute(f'ALTER TABLE {OLD}_version RENAME TO {NEW}_version')
    _assert_no_identifiers(OLD, 'upgrade')


def _rename_tag_source_back() -> None:
    op.execute(f'ALTER TABLE {NEW} RENAME TO {OLD}')
    op.execute(f'ALTER TABLE {NEW}_version RENAME TO {OLD}_version')
    _rename_identifiers(NEW, OLD)
    for table, old_column, new_column in COLUMN_RENAMES:
        # table names are the restored (old) ones by this point
        op.execute(f'ALTER TABLE {table} RENAME COLUMN {new_column} TO {old_column}')
    # Same guard as upgrade: fail here rather than leave a schema that is half
    # tag_source and half topic_entity_tag_source, which would otherwise only
    # surface later as a missing-column error at runtime.
    _assert_no_identifiers(NEW, 'downgrade')


def _normalise_curator_validation_type() -> None:
    """'professional_curator' -> 'professional_biocurator'.

    The two spellings were never both valid: only 'professional_biocurator'
    is what validation edges key on (ATP_ID_SOURCE_CURATOR). Runs before the
    backfill so a corrected source is the row the backfill then reuses.
    """
    op.execute(f"""
        UPDATE tag_source
           SET validation_type = '{ABC_VALIDATION_TYPE}'
         WHERE validation_type = 'professional_curator'
    """)


def _rewrite_saved_grid_layouts(old: str, new: str) -> None:
    """Rewrite AgGrid colIds saved in person_setting.json_settings.

    TopicEntityTable's column `field` values are the grid's colIds, and
    BiblioPreferenceControls persists columnState + filterModel per curator
    under component_name='tet_table'. Ten of those fields carry the source
    table's name, so renaming the table silently orphans every saved layout:
    hidden columns reappear and saved filters stop matching, with nothing to
    indicate why. 33 rows on prod and 35 on dev are affected (found in review -
    the first reviewer missed this because the grid also has in-memory-only
    column state, which is what it looked at).

    A plain string replace is correct for both shapes:
      topic_entity_tag_source.source_method -> tag_source.source_method
      topic_entity_tag_source.topic_entity_tag_source_id -> tag_source.tag_source_id
    """
    # A bare token replace, NOT anchored on the '.' prefix: the colId
    # topic_entity_tag_source.topic_entity_tag_source_id has to become
    # tag_source.tag_source_id, and an anchored replace would leave the suffix
    # stale. Both current shapes are covered, and the only colId embedding the
    # old name mid-string (topic_entity_tag.topic_entity_tag_source_id) also
    # maps correctly because the match starts at offset 17.
    #
    # Downgrade caveat: this direction rewrites every 'tag_source' occurrence,
    # so a colId that legitimately contains it for another reason (a future
    # curation_status_source_association.tag_source_id, say) would be mangled
    # for anyone who stays on the downgraded revision. A full
    # downgrade/re-upgrade round trip is clean. Accepted rather than anchored,
    # because anchoring breaks the real case above to guard a hypothetical one.
    op.execute(f"""
        UPDATE person_setting
           SET json_settings = replace(json_settings::text, '{old}', '{new}')::jsonb
         WHERE component_name = 'tet_table'
           AND json_settings::text LIKE '%{old}%'
    """)


def _backfill_abc_source_associations() -> None:
    """Stamp every existing curation_status row with its per-MOD ABC source.

    Written in SQL, so these rows get no continuum version row: history for a
    backfilled association starts at its first real edit. Re-attributing the
    WB-ported rows to their real source is SCRUM-6456, not this revision.
    """
    # 1. Ensure an ABC source exists for every MOD that has curation_status rows.
    #    The match is on the tag_source unique key, so it agrees with
    #    get_or_create_abc_source.
    op.execute(f"""
        INSERT INTO tag_source (source_evidence_assertion, source_method, validation_type,
                                description, data_provider, secondary_data_provider_id,
                                date_created, date_updated)
        SELECT '{ABC_ASSERTION}', '{ABC_METHOD}', '{ABC_VALIDATION_TYPE}',
               '{ABC_DESCRIPTION}', m.abbreviation, m.mod_id, NOW(), NOW()
          FROM mod m
         WHERE EXISTS (SELECT 1 FROM curation_status cs WHERE cs.mod_id = m.mod_id)
           AND NOT EXISTS (SELECT 1 FROM tag_source ts
                            WHERE ts.source_evidence_assertion = '{ABC_ASSERTION}'
                              AND ts.source_method = '{ABC_METHOD}'
                              AND ts.data_provider = m.abbreviation
                              AND ts.secondary_data_provider_id = m.mod_id)
    """)

    # 2. Stamp every curation_status row, mirroring its values and preserving
    #    its audit fields.
    op.execute(f"""
        INSERT INTO curation_status_source_association
               (curation_status_id, tag_source_id, curation_status, curation_tag, note,
                date_created, date_updated, created_by, updated_by)
        SELECT cs.curation_status_id, ts.tag_source_id,
               cs.curation_status, cs.curation_tag, cs.note,
               cs.date_created, cs.date_updated, cs.created_by, cs.updated_by
          FROM curation_status cs
          JOIN mod m ON m.mod_id = cs.mod_id
          JOIN tag_source ts
            ON ts.source_evidence_assertion = '{ABC_ASSERTION}'
           AND ts.source_method = '{ABC_METHOD}'
           AND ts.data_provider = m.abbreviation
           AND ts.secondary_data_provider_id = m.mod_id
        ON CONFLICT (curation_status_id, tag_source_id) DO NOTHING
    """)

    # 3. Fail loudly rather than half-backfill.
    op.execute("""
        DO $$
        DECLARE missing bigint;
        BEGIN
            SELECT count(*) INTO missing
              FROM curation_status cs
             WHERE NOT EXISTS (SELECT 1 FROM curation_status_source_association a
                                WHERE a.curation_status_id = cs.curation_status_id);
            IF missing > 0 THEN
                RAISE EXCEPTION 'ABC backfill left % curation_status rows unattributed', missing;
            END IF;
        END $$;
    """)


def upgrade():
    # The rename runs first: curation_status_source_association's FK targets
    # tag_source.tag_source_id, which does not exist under that name until now.
    _rename_source_table_to_tag_source()

    op.create_table('curation_status_source_association_version',
    sa.Column('curation_status_source_association_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('curation_status_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tag_source_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('curation_status', sa.String(), autoincrement=False, nullable=True),
    sa.Column('curation_tag', sa.String(), autoincrement=False, nullable=True),
    sa.Column('note', sa.String(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('curation_status_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tag_source_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('curation_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('curation_tag_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('curation_status_source_association_id', 'transaction_id')
    )
    op.create_index(op.f('ix_curation_status_source_association_version_curation_status_id'), 'curation_status_source_association_version', ['curation_status_id'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_version_date_created'), 'curation_status_source_association_version', ['date_created'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_version_date_updated'), 'curation_status_source_association_version', ['date_updated'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_version_end_transaction_id'), 'curation_status_source_association_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_version_operation_type'), 'curation_status_source_association_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_version_tag_source_id'), 'curation_status_source_association_version', ['tag_source_id'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_version_transaction_id'), 'curation_status_source_association_version', ['transaction_id'], unique=False)
    op.create_table('curation_status_version',
    sa.Column('curation_status_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.String(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('curation_status', sa.String(), autoincrement=False, nullable=True),
    sa.Column('curation_tag', sa.String(), autoincrement=False, nullable=True),
    sa.Column('note', sa.String(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('topic_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reference_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mod_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('curation_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('curation_tag_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('curation_status_id', 'transaction_id')
    )
    op.create_index(op.f('ix_curation_status_version_date_created'), 'curation_status_version', ['date_created'], unique=False)
    op.create_index(op.f('ix_curation_status_version_date_updated'), 'curation_status_version', ['date_updated'], unique=False)
    op.create_index(op.f('ix_curation_status_version_end_transaction_id'), 'curation_status_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_curation_status_version_mod_id'), 'curation_status_version', ['mod_id'], unique=False)
    op.create_index(op.f('ix_curation_status_version_operation_type'), 'curation_status_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_curation_status_version_reference_id'), 'curation_status_version', ['reference_id'], unique=False)
    op.create_index(op.f('ix_curation_status_version_topic'), 'curation_status_version', ['topic'], unique=False)
    op.create_index(op.f('ix_curation_status_version_transaction_id'), 'curation_status_version', ['transaction_id'], unique=False)
    op.create_table('curation_status_source_association',
    sa.Column('curation_status_source_association_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curation_status_id', sa.Integer(), nullable=False),
    sa.Column('tag_source_id', sa.Integer(), nullable=False),
    sa.Column('curation_status', sa.String(), nullable=True),
    sa.Column('curation_tag', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['curation_status_id'], ['curation_status.curation_status_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_source_id'], ['tag_source.tag_source_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('curation_status_source_association_id'),
    sa.UniqueConstraint('curation_status_id', 'tag_source_id', name='curation_status_source_association_unique')
    )
    op.create_index(op.f('ix_curation_status_source_association_curation_status_id'), 'curation_status_source_association', ['curation_status_id'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_date_created'), 'curation_status_source_association', ['date_created'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_date_updated'), 'curation_status_source_association', ['date_updated'], unique=False)
    op.create_index(op.f('ix_curation_status_source_association_tag_source_id'), 'curation_status_source_association', ['tag_source_id'], unique=False)

    _rewrite_saved_grid_layouts(OLD, NEW)
    _normalise_curator_validation_type()
    _backfill_abc_source_associations()


def downgrade():
    _rewrite_saved_grid_layouts(NEW, OLD)
    op.drop_table('curation_status_source_association')
    op.drop_table('curation_status_source_association_version')
    op.drop_table('curation_status_version')
    # The ABC tag_source rows the backfill may have created are deliberately
    # left in place: other data may already reference them. The validation_type
    # normalisation is deliberately NOT reversed either - 'professional_curator'
    # was always wrong, and restoring it would silently stop those sources'
    # curator validations from counting.
    _rename_tag_source_back()
