"""delete old mod ref type table

Revision ID: 29bbb556d6cf
Revises: 8026ae73cbf3
Create Date: 2022-11-01 22:37:07.966771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bbb556d6cf'
down_revision = '8026ae73cbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mod_reference_type_version_end_transaction_id', table_name='mod_reference_type_version')
    op.drop_index('ix_mod_reference_type_version_operation_type', table_name='mod_reference_type_version')
    op.drop_index('ix_mod_reference_type_version_reference_id', table_name='mod_reference_type_version')
    op.drop_index('ix_mod_reference_type_version_transaction_id', table_name='mod_reference_type_version')
    op.drop_table('mod_reference_type_version')
    op.drop_index('ix_mod_reference_type_reference_id', table_name='mod_reference_type')
    op.drop_table('mod_reference_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_reference_type',
    sa.Column('mod_reference_type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.reference_id'], name='mod_reference_types_reference_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mod_reference_type_id', name='mod_reference_type_pkey'),
    sa.UniqueConstraint('reference_id', 'reference_type', 'source', name='uniq_mrt')
    )
    op.create_index('ix_mod_reference_type_reference_id', 'mod_reference_type', ['reference_id'], unique=False)
    op.create_table('mod_reference_type_version',
    sa.Column('mod_reference_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reference_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reference_type_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('mod_reference_type_id', 'transaction_id', name='mod_reference_type_version_pkey')
    )
    op.create_index('ix_mod_reference_type_version_transaction_id', 'mod_reference_type_version', ['transaction_id'], unique=False)
    op.create_index('ix_mod_reference_type_version_reference_id', 'mod_reference_type_version', ['reference_id'], unique=False)
    op.create_index('ix_mod_reference_type_version_operation_type', 'mod_reference_type_version', ['operation_type'], unique=False)
    op.create_index('ix_mod_reference_type_version_end_transaction_id', 'mod_reference_type_version', ['end_transaction_id'], unique=False)
    # ### end Alembic commands ###
