"""references table renamed to reference

Revision ID: 2bbc6033143f
Revises: d09597a053bb
Create Date: 2022-05-04 11:05:32.607926

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '2bbc6033143f'
down_revision = 'd09597a053bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The table itself
    op.rename_table('references', 'reference')
    # its sequence
    op.execute('ALTER SEQUENCE references_reference_id_seq RENAME TO reference_reference_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX references_pkey RENAME TO reference_pkey')
    op.execute('ALTER INDEX ix_references_curie RENAME TO ix_reference_curie')
    op.execute('ALTER INDEX ix_references_resource_id RENAME TO ix_reference_resource_id')

    # version table
    op.rename_table('references_version', 'reference_version')
    # indexes
    op.execute('ALTER INDEX references_version_pkey RENAME TO reference_version_pkey')
    op.execute('ALTER INDEX ix_references_version_curie RENAME TO ix_reference_version_curie')
    op.execute('ALTER INDEX ix_references_version_end_transaction_id RENAME TO ix_reference_version_end_transaction_id')
    op.execute('ALTER INDEX ix_references_version_operation_type RENAME TO ix_reference_version_operation_type')
    op.execute('ALTER INDEX ix_references_version_resource_id RENAME TO ix_reference_version_resource_id')
    op.execute('ALTER INDEX ix_references_version_transaction_id RENAME TO ix_reference_version_transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The table itself
    op.rename_table('reference', 'references')
    # its sequence
    op.execute('ALTER SEQUENCE reference_reference_id_seq RENAME TO references_reference_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX reference_pkey RENAME TO references_pkey')
    op.execute('ALTER INDEX ix_reference_orcid RENAME TO ix_references_orcid')
    op.execute('ALTER INDEX ix_reference_resource_id RENAME TO ix_references_resource_id')

    # version table
    op.rename_table('reference_version', 'references_version')
    # indexes
    op.execute('ALTER INDEX reference_version_pkey RENAME TO references_version_pkey')
    op.execute('ALTER INDEX ix_reference_version_curie RENAME TO ix_references_version_curie')
    op.execute('ALTER INDEX ix_reference_version_end_transaction_id RENAME TO ix_references_version_end_transaction_id')
    op.execute('ALTER INDEX ix_reference_version_operation_type RENAME TO ix_references_version_operation_type')
    op.execute('ALTER INDEX ix_reference_version_resource_id RENAME TO ix_references_version_resource_id')
    op.execute('ALTER INDEX ix_reference_version_transaction_id RENAME TO ix_references_version_transaction_id')
    # ### end Alembic commands ###
