"""topic_entity_tag

Revision ID: 3b6a5e1a1b4b
Revises: a8baf52cb7c2
Create Date: 2022-08-03 08:55:45.259575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6a5e1a1b4b'
down_revision = 'a8baf52cb7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'topic_entity_tag_prop_version',
        sa.Column('topic_entity_tag_prop_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('topic_entity_tag_id', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('qualifier', sa.String(), autoincrement=False, nullable=True),
        sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
        sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
        sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.Column('topic_entity_tag_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('qualifier_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.PrimaryKeyConstraint('topic_entity_tag_prop_id', 'transaction_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_prop_version_end_transaction_id'), 'topic_entity_tag_prop_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_prop_version_operation_type'), 'topic_entity_tag_prop_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_prop_version_topic_entity_tag_id'), 'topic_entity_tag_prop_version', ['topic_entity_tag_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_prop_version_transaction_id'), 'topic_entity_tag_prop_version', ['transaction_id'], unique=False)
    op.create_table(
        'topic_entity_tag_version',
        sa.Column('topic_entity_tag_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('reference_id', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('topic', sa.String(), autoincrement=False, nullable=True),
        sa.Column('entity_type', sa.String(), autoincrement=False, nullable=True),
        sa.Column('alliance_entity', sa.String(), autoincrement=False, nullable=True),
        sa.Column('mod_entity', sa.String(), autoincrement=False, nullable=True),
        sa.Column('new_entity', sa.String(), autoincrement=False, nullable=True),
        sa.Column('taxon', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('note', sa.String(), autoincrement=False, nullable=True),
        sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
        sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
        sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.Column('reference_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('topic_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('entity_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('alliance_entity_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('mod_entity_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('new_entity_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('taxon_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('note_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.PrimaryKeyConstraint('topic_entity_tag_id', 'transaction_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_version_end_transaction_id'), 'topic_entity_tag_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_version_operation_type'), 'topic_entity_tag_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_version_reference_id'), 'topic_entity_tag_version', ['reference_id'], unique=False)
    op.create_index(op.f('ix_topic_entity_tag_version_transaction_id'), 'topic_entity_tag_version', ['transaction_id'], unique=False)
    op.create_table(
        'topic_entity_tag',
        sa.Column('topic_entity_tag_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reference_id', sa.Integer(), nullable=False),
        sa.Column('topic', sa.String(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('alliance_entity', sa.String(), nullable=True),
        sa.Column('mod_entity', sa.String(), nullable=True),
        sa.Column('new_entity', sa.String(), nullable=True),
        sa.Column('taxon', sa.Integer(), nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('date_updated', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['reference_id'], ['reference.reference_id'], ),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('topic_entity_tag_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_reference_id'), 'topic_entity_tag', ['reference_id'], unique=False)
    op.create_table(
        'topic_entity_tag_prop',
        sa.Column('topic_entity_tag_prop_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('topic_entity_tag_id', sa.Integer(), nullable=False),
        sa.Column('qualifier', sa.String(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('date_updated', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['topic_entity_tag_id'], ['topic_entity_tag.topic_entity_tag_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('topic_entity_tag_prop_id')
    )
    op.create_index(op.f('ix_topic_entity_tag_prop_topic_entity_tag_id'), 'topic_entity_tag_prop', ['topic_entity_tag_id'], unique=False)
    op.alter_column(
        'workflow_tag_version', 'workflow_tag_id',
        existing_type=sa.VARCHAR(),
        nullable=True,
        autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'workflow_tag_version', 'workflow_tag_id',
        existing_type=sa.VARCHAR(),
        nullable=False,
        autoincrement=False)
    op.drop_index(op.f('ix_topic_entity_tag_prop_topic_entity_tag_id'), table_name='topic_entity_tag_prop')
    op.drop_table('topic_entity_tag_prop')
    op.drop_index(op.f('ix_topic_entity_tag_reference_id'), table_name='topic_entity_tag')
    op.drop_table('topic_entity_tag')
    op.drop_index(op.f('ix_topic_entity_tag_version_transaction_id'), table_name='topic_entity_tag_version')
    op.drop_index(op.f('ix_topic_entity_tag_version_reference_id'), table_name='topic_entity_tag_version')
    op.drop_index(op.f('ix_topic_entity_tag_version_operation_type'), table_name='topic_entity_tag_version')
    op.drop_index(op.f('ix_topic_entity_tag_version_end_transaction_id'), table_name='topic_entity_tag_version')
    op.drop_table('topic_entity_tag_version')
    op.drop_index(op.f('ix_topic_entity_tag_prop_version_transaction_id'), table_name='topic_entity_tag_prop_version')
    op.drop_index(op.f('ix_topic_entity_tag_prop_version_topic_entity_tag_id'), table_name='topic_entity_tag_prop_version')
    op.drop_index(op.f('ix_topic_entity_tag_prop_version_operation_type'), table_name='topic_entity_tag_prop_version')
    op.drop_index(op.f('ix_topic_entity_tag_prop_version_end_transaction_id'), table_name='topic_entity_tag_prop_version')
    op.drop_table('topic_entity_tag_prop_version')
    # ### end Alembic commands ###
