"""remodeling cross_reference_author_editor

Revision ID: 44745739833b
Revises: fbd067b9e403
Create Date: 2022-10-21 23:01:29.678350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44745739833b'
down_revision = 'fbd067b9e403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_orcid_fkey', 'author', type_='foreignkey')
    op.add_column('cross_reference', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('cross_reference', sa.Column('cross_reference_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('cross_reference', sa.Column('curie_prefix', sa.String(), nullable=False))
    op.add_column('cross_reference', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('cross_reference', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('cross_reference', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_index('idx_curie', 'cross_reference', ['curie'], unique=True, postgresql_where=sa.text('is_obsolete IS false'))
    op.create_index('idx_curie_prefix_reference', 'cross_reference', ['curie_prefix', 'reference_id'], unique=True, postgresql_where=sa.text('is_obsolete IS false'))
    op.create_index('idx_curie_prefix_resource', 'cross_reference', ['curie_prefix', 'resource_id'], unique=True, postgresql_where=sa.text('is_obsolete IS false'))
    op.create_index(op.f('ix_cross_reference_curie'), 'cross_reference', ['curie'], unique=False)
    op.create_foreign_key(None, 'cross_reference', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'cross_reference', 'users', ['updated_by'], ['id'])
    op.add_column('cross_reference_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('cross_reference_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cross_reference_version', sa.Column('cross_reference_id', sa.Integer(), autoincrement=False, nullable=False))
    op.add_column('cross_reference_version', sa.Column('curie_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cross_reference_version', sa.Column('curie_prefix', sa.String(), autoincrement=False, nullable=True))
    op.add_column('cross_reference_version', sa.Column('curie_prefix_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cross_reference_version', sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('cross_reference_version', sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cross_reference_version', sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('cross_reference_version', sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cross_reference_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('cross_reference_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('cross_reference_version', 'curie',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    op.create_index(op.f('ix_cross_reference_version_curie'), 'cross_reference_version', ['curie'], unique=False)
    op.create_index(op.f('ix_editor_orcid'), 'editor', ['orcid'], unique=False)
    op.drop_constraint('editors_orcid_fkey', 'editor', type_='foreignkey')
    op.create_index(op.f('ix_editor_version_orcid'), 'editor_version', ['orcid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editor_version_orcid'), table_name='editor_version')
    op.create_foreign_key('editors_orcid_fkey', 'editor', 'cross_reference', ['orcid'], ['curie'])
    op.drop_index(op.f('ix_editor_orcid'), table_name='editor')
    op.drop_index(op.f('ix_cross_reference_version_curie'), table_name='cross_reference_version')
    op.alter_column('cross_reference_version', 'curie',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    op.drop_column('cross_reference_version', 'updated_by_mod')
    op.drop_column('cross_reference_version', 'updated_by')
    op.drop_column('cross_reference_version', 'date_updated_mod')
    op.drop_column('cross_reference_version', 'date_updated')
    op.drop_column('cross_reference_version', 'date_created_mod')
    op.drop_column('cross_reference_version', 'date_created')
    op.drop_column('cross_reference_version', 'curie_prefix_mod')
    op.drop_column('cross_reference_version', 'curie_prefix')
    op.drop_column('cross_reference_version', 'curie_mod')
    op.drop_column('cross_reference_version', 'cross_reference_id')
    op.drop_column('cross_reference_version', 'created_by_mod')
    op.drop_column('cross_reference_version', 'created_by')
    op.drop_constraint(None, 'cross_reference', type_='foreignkey')
    op.drop_constraint(None, 'cross_reference', type_='foreignkey')
    op.drop_index(op.f('ix_cross_reference_curie'), table_name='cross_reference')
    op.drop_index('idx_curie_prefix_resource', table_name='cross_reference')
    op.drop_index('idx_curie_prefix_reference', table_name='cross_reference')
    op.drop_index('idx_curie', table_name='cross_reference')
    op.drop_column('cross_reference', 'updated_by')
    op.drop_column('cross_reference', 'date_updated')
    op.drop_column('cross_reference', 'date_created')
    op.drop_column('cross_reference', 'curie_prefix')
    op.drop_column('cross_reference', 'cross_reference_id')
    op.drop_column('cross_reference', 'created_by')
    op.create_foreign_key('authors_orcid_fkey', 'author', 'cross_reference', ['orcid'], ['curie'])
    # ### end Alembic commands ###
