"""citation

Revision ID: 4c2127d5c55f
Revises: d8f2bbb1dc93
Create Date: 2023-03-20 16:18:44.757443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2127d5c55f'
down_revision = 'd8f2bbb1dc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference', 'citation')
    op.drop_column('reference_version', 'citation_mod')
    op.drop_column('reference_version', 'citation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_version', sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('citation_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('reference', sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
