"""add unique constraints to crossRef

Revision ID: 5015b233f2a1
Revises: 8eceb3502d48
Create Date: 2022-10-25 03:27:12.866005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5015b233f2a1'
down_revision = '8eceb3502d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cross_reference', 'curie_prefix',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('cross_reference', 'date_created',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.create_index('idx_curie', 'cross_reference', ['curie'], unique=True, postgresql_where=sa.text('is_obsolete IS false'))
    op.create_index('idx_curie_prefix_reference', 'cross_reference', ['curie_prefix', 'reference_id'], unique=True, postgresql_where=sa.text('is_obsolete IS false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_curie_prefix_reference', table_name='cross_reference')
    op.drop_index('idx_curie', table_name='cross_reference')
    op.alter_column('cross_reference', 'date_created',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('cross_reference', 'curie_prefix',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
