"""automatic_who_and_when

Revision ID: 6b245dc1afdc
Revises: bf1c8d2663b4
Create Date: 2022-08-23 20:53:30.919627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b245dc1afdc'
down_revision = 'bf1c8d2663b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('author', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'author', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'author', 'users', ['updated_by'], ['id'])
    op.add_column('author_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('author_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('author_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('author_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('editor', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('editor', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'editor', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'editor', 'users', ['updated_by'], ['id'])
    op.add_column('editor_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('editor_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('editor_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('editor_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mod', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('mod', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'mod', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'mod', 'users', ['updated_by'], ['id'])
    op.add_column('mod_corpus_association', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('mod_corpus_association', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'mod_corpus_association', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'mod_corpus_association', 'users', ['created_by'], ['id'])
    op.add_column('mod_corpus_association_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('mod_corpus_association_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mod_corpus_association_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('mod_corpus_association_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mod_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('mod_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mod_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('mod_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('reference', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('reference', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'reference', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'reference', 'users', ['created_by'], ['id'])
    op.add_column('reference_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('reference_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('resource', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('resource', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'resource', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'resource', 'users', ['updated_by'], ['id'])
    op.add_column('resource_version', sa.Column('created_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('resource_version', sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('resource_version', sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True))
    op.add_column('resource_version', sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('topic_entity_tag', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('topic_entity_tag_prop', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workflow_tag', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_tag', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('topic_entity_tag_prop', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('topic_entity_tag', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('resource_version', 'updated_by_mod')
    op.drop_column('resource_version', 'updated_by')
    op.drop_column('resource_version', 'created_by_mod')
    op.drop_column('resource_version', 'created_by')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'updated_by')
    op.drop_column('resource', 'created_by')
    op.drop_column('reference_version', 'updated_by_mod')
    op.drop_column('reference_version', 'updated_by')
    op.drop_column('reference_version', 'created_by_mod')
    op.drop_column('reference_version', 'created_by')
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.drop_column('reference', 'updated_by')
    op.drop_column('reference', 'created_by')
    op.drop_column('mod_version', 'updated_by_mod')
    op.drop_column('mod_version', 'updated_by')
    op.drop_column('mod_version', 'created_by_mod')
    op.drop_column('mod_version', 'created_by')
    op.drop_column('mod_corpus_association_version', 'updated_by_mod')
    op.drop_column('mod_corpus_association_version', 'updated_by')
    op.drop_column('mod_corpus_association_version', 'created_by_mod')
    op.drop_column('mod_corpus_association_version', 'created_by')
    op.drop_constraint(None, 'mod_corpus_association', type_='foreignkey')
    op.drop_constraint(None, 'mod_corpus_association', type_='foreignkey')
    op.drop_column('mod_corpus_association', 'updated_by')
    op.drop_column('mod_corpus_association', 'created_by')
    op.drop_constraint(None, 'mod', type_='foreignkey')
    op.drop_constraint(None, 'mod', type_='foreignkey')
    op.drop_column('mod', 'updated_by')
    op.drop_column('mod', 'created_by')
    op.drop_column('editor_version', 'updated_by_mod')
    op.drop_column('editor_version', 'updated_by')
    op.drop_column('editor_version', 'created_by_mod')
    op.drop_column('editor_version', 'created_by')
    op.drop_constraint(None, 'editor', type_='foreignkey')
    op.drop_constraint(None, 'editor', type_='foreignkey')
    op.drop_column('editor', 'updated_by')
    op.drop_column('editor', 'created_by')
    op.drop_column('author_version', 'updated_by_mod')
    op.drop_column('author_version', 'updated_by')
    op.drop_column('author_version', 'created_by_mod')
    op.drop_column('author_version', 'created_by')
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'updated_by')
    op.drop_column('author', 'created_by')
    # ### end Alembic commands ###
