"""updated referencefile unique constraint

Revision ID: 6b6ddbfbfb48
Revises: 6d4bd4ccde96
Create Date: 2022-11-07 19:12:07.618020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6ddbfbfb48'
down_revision = '6d4bd4ccde96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reference_id_display_name', table_name='referencefile')
    op.create_index('idx_reference_id_display_name', 'referencefile', ['reference_id', 'display_name', 'file_extension'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reference_id_display_name', table_name='referencefile')
    op.create_index('idx_reference_id_display_name', 'referencefile', ['reference_id', 'display_name'], unique=True)
    # ### end Alembic commands ###
