"""reference_citation
Revision ID: 7d68b38fe026
Revises: 7f3f27c162c4
Create Date: 2022-07-21 09:05:44.960963
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d68b38fe026'
down_revision = '7f3f27c162c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('citation', sa.String(), nullable=True))
    op.add_column('reference_version', sa.Column('citation', sa.String(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('citation_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_version', 'citation_mod')
    op.drop_column('reference_version', 'citation')
    op.drop_column('reference', 'citation')
    # ### end Alembic commands ###
