"""add reference_mod_md5sum

Revision ID: 8026ae73cbf3
Revises: 176245023ef7
Create Date: 2022-10-31 18:39:31.791834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8026ae73cbf3'
down_revision = '176245023ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_mod_md5sum',
    sa.Column('reference_mod_md5sum_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('md5sum', sa.String(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['reference.reference_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reference_mod_md5sum_id'),
    sa.UniqueConstraint('md5sum')
    )
    op.create_index(op.f('ix_reference_mod_md5sum_mod_id'), 'reference_mod_md5sum', ['mod_id'], unique=False)
    op.create_index(op.f('ix_reference_mod_md5sum_reference_id'), 'reference_mod_md5sum', ['reference_id'], unique=False)
    op.create_index('uix_reference_id', 'reference_mod_md5sum', ['reference_id'], unique=True, postgresql_where=sa.text('mod_id IS NULL'))
    op.create_index('uix_reference_id_mod_id', 'reference_mod_md5sum', ['reference_id', 'mod_id'], unique=True, postgresql_where=sa.text('mod_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_reference_id_mod_id', table_name='reference_mod_md5sum')
    op.drop_index('uix_reference_id', table_name='reference_mod_md5sum')
    op.drop_index(op.f('ix_reference_mod_md5sum_reference_id'), table_name='reference_mod_md5sum')
    op.drop_index(op.f('ix_reference_mod_md5sum_mod_id'), table_name='reference_mod_md5sum')
    op.drop_table('reference_mod_md5sum')
    # ### end Alembic commands ###
