"""scrum-1492

Revision ID: 8c924433c42e
Revises: ac27c31b0ab4
Create Date: 2022-04-26 09:23:48.282263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c924433c42e'
down_revision = 'ac27c31b0ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_version_end_transaction_id', table_name='notes_version')
    op.drop_index('ix_notes_version_operation_type', table_name='notes_version')
    op.drop_index('ix_notes_version_reference_id', table_name='notes_version')
    op.drop_index('ix_notes_version_resource_id', table_name='notes_version')
    op.drop_index('ix_notes_version_transaction_id', table_name='notes_version')
    op.drop_table('notes_version')
    op.drop_index('ix_notes_reference_id', table_name='notes')
    op.drop_index('ix_notes_resource_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_files_version_end_transaction_id', table_name='files_version')
    op.drop_index('ix_files_version_md5sum', table_name='files_version')
    op.drop_index('ix_files_version_operation_type', table_name='files_version')
    op.drop_index('ix_files_version_reference_id', table_name='files_version')
    op.drop_index('ix_files_version_transaction_id', table_name='files_version')
    op.drop_table('files_version')
    op.drop_index('ix_files_md5sum', table_name='files')
    op.drop_index('ix_files_reference_id', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_authors_resource_id', table_name='authors')
    op.drop_constraint('authors_resource_id_fkey', 'authors', type_='foreignkey')
    op.drop_column('authors', 'middle_names')
    op.drop_column('authors', 'resource_id')
    op.drop_index('ix_authors_version_resource_id', table_name='authors_version')
    op.drop_column('authors_version', 'resource_id_mod')
    op.drop_column('authors_version', 'middle_names_mod')
    op.drop_column('authors_version', 'middle_names')
    op.drop_column('authors_version', 'resource_id')
    op.drop_index('ix_editors_reference_id', table_name='editors')
    op.drop_constraint('editors_reference_id_fkey', 'editors', type_='foreignkey')
    op.drop_column('editors', 'middle_names')
    op.drop_column('editors', 'reference_id')
    op.drop_index('ix_editors_version_reference_id', table_name='editors_version')
    op.drop_column('editors_version', 'reference_id_mod')
    op.drop_column('editors_version', 'middle_names_mod')
    op.drop_column('editors_version', 'middle_names')
    op.drop_column('editors_version', 'reference_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editors_version', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('editors_version', sa.Column('middle_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('editors_version', sa.Column('middle_names_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('editors_version', sa.Column('reference_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_editors_version_reference_id', 'editors_version', ['reference_id'], unique=False)
    op.add_column('editors', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('editors', sa.Column('middle_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_foreign_key('editors_reference_id_fkey', 'editors', 'references', ['reference_id'], ['reference_id'], ondelete='CASCADE')
    op.create_index('ix_editors_reference_id', 'editors', ['reference_id'], unique=False)
    op.add_column('authors_version', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors_version', sa.Column('middle_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('authors_version', sa.Column('middle_names_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('authors_version', sa.Column('resource_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_authors_version_resource_id', 'authors_version', ['resource_id'], unique=False)
    op.add_column('authors', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('middle_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_foreign_key('authors_resource_id_fkey', 'authors', 'resources', ['resource_id'], ['resource_id'])
    op.create_index('ix_authors_resource_id', 'authors', ['resource_id'], unique=False)
    op.create_table('files',
    sa.Column('file_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s3_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('primary', 'primary_figure', 'supplemental', 'supplemental_figure', name='filecategories'), autoincrement=False, nullable=True),
    sa.Column('folder', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mod_submitted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mods_permitted', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('institutes_permitted', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reference_id'], ['references.reference_id'], name='files_reference_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', name='files_pkey'),
    sa.UniqueConstraint('s3_filename', name='files_s3_filename_key')
    )
    op.create_index('ix_files_reference_id', 'files', ['reference_id'], unique=False)
    op.create_index('ix_files_md5sum', 'files', ['md5sum'], unique=False)
    op.create_table('files_version',
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s3_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('primary', 'primary_figure', 'supplemental', 'supplemental_figure', name='filecategories'), autoincrement=False, nullable=True),
    sa.Column('folder', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('md5sum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('mod_submitted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mods_permitted', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('institutes_permitted', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('s3_filename_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reference_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('extension_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('language_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('content_type_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('category_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('folder_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('md5sum_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('size_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('display_name_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('upload_date_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('public_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mod_submitted_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mods_permitted_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('institutes_permitted_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('file_id', 'transaction_id', name='files_version_pkey')
    )
    op.create_index('ix_files_version_transaction_id', 'files_version', ['transaction_id'], unique=False)
    op.create_index('ix_files_version_reference_id', 'files_version', ['reference_id'], unique=False)
    op.create_index('ix_files_version_operation_type', 'files_version', ['operation_type'], unique=False)
    op.create_index('ix_files_version_md5sum', 'files_version', ['md5sum'], unique=False)
    op.create_index('ix_files_version_end_transaction_id', 'files_version', ['end_transaction_id'], unique=False)
    op.create_table('notes',
    sa.Column('note_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.reference_id'], name='notes_reference_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name='notes_resource_id_fkey'),
    sa.PrimaryKeyConstraint('note_id', name='notes_pkey')
    )
    op.create_index('ix_notes_resource_id', 'notes', ['resource_id'], unique=False)
    op.create_index('ix_notes_reference_id', 'notes', ['reference_id'], unique=False)
    op.create_table('notes_version',
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reference_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('resource_id_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('note_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('name_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('date_created_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('note_id', 'transaction_id', name='notes_version_pkey')
    )
    op.create_index('ix_notes_version_transaction_id', 'notes_version', ['transaction_id'], unique=False)
    op.create_index('ix_notes_version_resource_id', 'notes_version', ['resource_id'], unique=False)
    op.create_index('ix_notes_version_reference_id', 'notes_version', ['reference_id'], unique=False)
    op.create_index('ix_notes_version_operation_type', 'notes_version', ['operation_type'], unique=False)
    op.create_index('ix_notes_version_end_transaction_id', 'notes_version', ['end_transaction_id'], unique=False)
    # ### end Alembic commands ###
