"""allowing multiple referencefiles with same md5sum

Revision ID: 901d4fc6649a
Revises: 6b6ddbfbfb48
Create Date: 2022-11-15 02:46:20.413066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901d4fc6649a'
down_revision = '6b6ddbfbfb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_md5sum_reference_id', 'referencefile', ['md5sum', 'reference_id'], unique=True)
    op.drop_index('idx_md5sum', table_name='referencefile')
    op.create_index('idx_md5sum', 'referencefile', ['md5sum'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_md5sum', table_name='referencefile')
    op.create_index('idx_md5sum', 'referencefile', ['md5sum'], unique=True)
    op.drop_index('idx_md5sum_reference_id', table_name='referencefile')
    # ### end Alembic commands ###
