"""reference date published start end

Revision ID: 92d11d28775c
Revises: 5471c0ac2e0a
Create Date: 2022-10-07 00:56:06.037187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d11d28775c'
down_revision = '5471c0ac2e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('date_published_start', sa.DateTime(), nullable=True))
    op.add_column('reference', sa.Column('date_published_end', sa.DateTime(), nullable=True))
    op.add_column('reference_version', sa.Column('date_published_start', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('date_published_start_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('reference_version', sa.Column('date_published_end', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('date_published_end_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_version', 'date_published_start_mod')
    op.drop_column('reference_version', 'date_published_start')
    op.drop_column('reference_version', 'date_published_end_mod')
    op.drop_column('reference_version', 'date_published_end')
    op.drop_column('reference', 'date_published_start')
    op.drop_column('reference', 'date_published_end')
    # ### end Alembic commands ###
