"""open_access

Revision ID: a225a372e770
Revises: 63c8124a3a6b
Create Date: 2023-03-13 16:56:28.250028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a225a372e770'
down_revision = '63c8124a3a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copyright_license', sa.Column('open_access', sa.Boolean(), nullable=False))
    op.add_column('copyright_license_version', sa.Column('open_access', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('copyright_license_version', sa.Column('open_access_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('reference', 'open_access')
    op.drop_column('reference_version', 'open_access')
    op.drop_column('reference_version', 'open_access_mod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_version', sa.Column('open_access_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('reference_version', sa.Column('open_access', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reference', sa.Column('open_access', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('copyright_license_version', 'open_access_mod')
    op.drop_column('copyright_license_version', 'open_access')
    op.drop_column('copyright_license', 'open_access')
    # ### end Alembic commands ###
