"""constraint modreftype

Revision ID: a76ad65b5737
Revises: cf1a61f4dc91
Create Date: 2022-08-05 07:51:24.532217

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a76ad65b5737'
down_revision = 'cf1a61f4dc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_mrt', 'mod_reference_type', ['reference_id', 'reference_type', 'source'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_mrt', 'mod_reference_type', type_='unique')
    # ### end Alembic commands ###
