"""reference ontology

Revision ID: a8baf52cb7c2
Revises: 7d68b38fe026
Create Date: 2022-07-25 16:55:23.341689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8baf52cb7c2'
down_revision = '7d68b38fe026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reference_ontology_version',
        sa.Column('reference_ontology_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('reference_id', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('ontology_id', sa.String(), autoincrement=False, nullable=True),
        sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('date_created', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('date_updated', sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column('created_by', sa.String(), autoincrement=False, nullable=True),
        sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
        sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.Column('reference_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('ontology_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('mod_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('date_created_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('date_updated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('updated_by_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.PrimaryKeyConstraint('reference_ontology_id', 'transaction_id')
    )
    op.create_index(op.f('ix_reference_ontology_version_end_transaction_id'), 'reference_ontology_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_reference_ontology_version_operation_type'), 'reference_ontology_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_reference_ontology_version_reference_id'), 'reference_ontology_version', ['reference_id'], unique=False)
    op.create_index(op.f('ix_reference_ontology_version_transaction_id'), 'reference_ontology_version', ['transaction_id'], unique=False)
    op.create_table(
        'reference_ontology',
        sa.Column('reference_ontology_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reference_id', sa.Integer(), nullable=False),
        sa.Column('ontology_id', sa.String(), nullable=False),
        sa.Column('mod_id', sa.Integer(), nullable=True),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('date_updated', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['mod_id'], ['mod.mod_id'], ),
        sa.ForeignKeyConstraint(['reference_id'], ['reference.reference_id'], ),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('reference_ontology_id')
    )
    op.create_index(op.f('ix_reference_ontology_reference_id'), 'reference_ontology', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_ontology_reference_id'), table_name='reference_ontology')
    op.drop_table('reference_ontology')
    op.drop_index(op.f('ix_reference_ontology_version_transaction_id'), table_name='reference_ontology_version')
    op.drop_index(op.f('ix_reference_ontology_version_reference_id'), table_name='reference_ontology_version')
    op.drop_index(op.f('ix_reference_ontology_version_operation_type'), table_name='reference_ontology_version')
    op.drop_index(op.f('ix_reference_ontology_version_end_transaction_id'), table_name='reference_ontology_version')
    op.drop_table('reference_ontology_version')
    # ### end Alembic commands ###
