
"""fix datePublishedStart/end type to String()
Revision ID: bde1da8c5ccc
Revises: 1a834449762c
Create Date: 2023-02-27 04:46:24.259740
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'bde1da8c5ccc'
down_revision = '1a834449762c'
branch_labels = None
depends_on = None
def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###