"""Add a automated_alliance to modcorpussortsourcetype

Revision ID: bf1c8d2663b4
Revises: a76ad65b5737
Create Date: 2022-08-12 21:56:09.413721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1c8d2663b4'
down_revision = 'a76ad65b5737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE modcorpussortsourcetype ADD VALUE IF NOT EXISTS 'Automated_alliance' AFTER 'Manual_creation'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
