"""taxon, int to str

Revision ID: cf1a61f4dc91
Revises: f9ffa0de6064
Create Date: 2022-08-04 08:19:55.609112

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cf1a61f4dc91'
down_revision = 'f9ffa0de6064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE mod_taxon
        ALTER COLUMN taxon TYPE VARCHAR""")
    op.execute("""
        ALTER TABLE topic_entity_tag
        ALTER COLUMN taxon TYPE VARCHAR""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
