"""cross_references table renames cross_reference

Revision ID: d9c48be2f4d2
Revises: c5edf0d9f2d4
Create Date: 2022-05-02 09:08:31.900928

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9c48be2f4d2'
down_revision = 'c5edf0d9f2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The table itself
    op.rename_table('cross_references', 'cross_reference')
    # its sequence
    #     has none
    # Its Indexes
    op.execute('ALTER INDEX cross_references_pkey  RENAME TO cross_reference_pkey')
    op.execute('ALTER INDEX ix_cross_references_reference_id RENAME TO ix_cross_reference_reference_id')
    op.execute('ALTER INDEX ix_cross_references_resource_id RENAME TO ix_cross_reference_resource_id')
    # the version table
    op.rename_table('cross_references_version', 'cross_reference_version')
    # its indexes
    op.execute('ALTER INDEX cross_references_version_pkey RENAME TO cross_reference_version_pkey')
    op.execute('ALTER INDEX ix_cross_references_version_end_transaction_id RENAME TO ix_cross_reference_version_end_transaction_id')
    op.execute('ALTER INDEX ix_cross_references_version_operation_type RENAME TO ix_cross_reference_version_operation_type')
    op.execute('ALTER INDEX ix_cross_references_version_reference_id RENAME TO ix_cross_reference_version_reference_id')
    op.execute('ALTER INDEX ix_cross_references_version_resource_id RENAME TO ix_cross_reference_version_resource_id')
    op.execute('ALTER INDEX ix_cross_references_version_transaction_id RENAME TO ix_cross_reference_version_transaction_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The table itself
    op.rename_table('cross_references', 'cross_reference')
    # its sequence
    #     has none
    # Its Indexes
    op.execute('ALTER INDEX cross_reference_pkey  RENAME TO cross_references_pkey')
    op.execute('ALTER INDEX ix_cross_reference_reference_id RENAME TO ix_cross_references_reference_id')
    op.execute('ALTER INDEX ix_cross_reference_resource_id RENAME TO ix_cross_references_resource_id')
    # the version table
    op.rename_table('cross_reference_version', 'cross_references_version')
    # its indexes
    op.execute('ALTER INDEX cross_reference_version_pkey RENAME TO cross_references_version_pkey')
    op.execute('ALTER INDEX ix_cross_reference_version_end_transaction_id RENAME TO ix_cross_references_version_end_transaction_id')
    op.execute('ALTER INDEX ix_cross_reference_version_operation_type RENAME TO ix_cross_references_version_operation_type')
    op.execute('ALTER INDEX ix_cross_reference_version_reference_id RENAME TO ix_cross_references_version_reference_id')
    op.execute('ALTER INDEX ix_cross_reference_version_resource_id RENAME TO ix_cross_references_version_resource_id')
    op.execute('ALTER INDEX ix_cross_reference_version_transaction_id RENAME TO ix_cross_references_version_transaction_id')
    # ### end Alembic commands ###
