"""added copyright_license table

Revision ID: dbb7862ac37d
Revises: 901d4fc6649a
Create Date: 2023-02-09 20:51:31.109182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb7862ac37d'
down_revision = '901d4fc6649a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copyright_license',
    sa.Column('copyright_license_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('copyright_license_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('copyright_license_version',
    sa.Column('copyright_license_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('url', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('url_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('copyright_license_id', 'transaction_id')
    )
    op.create_index(op.f('ix_copyright_license_version_end_transaction_id'), 'copyright_license_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_copyright_license_version_operation_type'), 'copyright_license_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_copyright_license_version_transaction_id'), 'copyright_license_version', ['transaction_id'], unique=False)
    op.add_column('reference', sa.Column('copyright_license_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reference_copyright_license_id'), 'reference', ['copyright_license_id'], unique=False)
    op.create_foreign_key(None, 'reference', 'copyright_license', ['copyright_license_id'], ['copyright_license_id'])
    op.add_column('reference_version', sa.Column('copyright_license_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('reference_version', sa.Column('copyright_license_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_reference_version_copyright_license_id'), 'reference_version', ['copyright_license_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_version_copyright_license_id'), table_name='reference_version')
    op.drop_column('reference_version', 'copyright_license_id_mod')
    op.drop_column('reference_version', 'copyright_license_id')
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.drop_index(op.f('ix_reference_copyright_license_id'), table_name='reference')
    op.drop_column('reference', 'copyright_license_id')
    op.drop_index(op.f('ix_copyright_license_version_transaction_id'), table_name='copyright_license_version')
    op.drop_index(op.f('ix_copyright_license_version_operation_type'), table_name='copyright_license_version')
    op.drop_index(op.f('ix_copyright_license_version_end_transaction_id'), table_name='copyright_license_version')
    op.drop_table('copyright_license_version')
    op.drop_table('copyright_license')
    # ### end Alembic commands ###
