"""add correction and obsolete to reference category

Revision ID: ea142abf61a0
Revises: 951d7c11dbcd
Create Date: 2022-06-01 18:31:41.613384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea142abf61a0'
down_revision = '951d7c11dbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE referencecategory ADD VALUE IF NOT EXISTS 'Correction' AFTER 'Retraction'")
    op.execute("ALTER TYPE referencecategory ADD VALUE IF NOT EXISTS 'Obsolete' AFTER 'Retraction'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
