version: "3.7"

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    restart: always
    command: redis-server --requirepass "${REDIS_AUTH}"
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
     - REDIS_REPLICATION_MODE=master
    ports:
       - '6379:6379'

volumes:
    agr-literature-redis-data: