ARG ALLIANCE_RELEASE=latest
ARG REG=agrdocker
FROM ${REG}/agr_literature_env:${ALLIANCE_RELEASE}

ADD backend/app/requirements.dev.txt .

RUN pip3 install -r requirements.dev.txt

RUN apt -y install zsh

CMD ["python3" "-m pip3" "list"]
