ARG ALLIANCE_RELEASE=latest
ARG REG=agrdocker
FROM ${REG}/agr_base_linux_env:${ALLIANCE_RELEASE}

ADD backend/app/requirements.txt .

RUN apt update
RUN apt install graphviz -y

RUN pip3 install -r requirements.txt

ARG aws_access_key_id=
ARG aws_secret_access_key=
ARG okta_client_id=
ARG okta_client_secret=

ENV PYTHONPATH="/workdir/src/xml_processing" \
    XML_PATH="/workdir/src/xml_processing/" \
    API_PORT=8080 \
    OKTA_CLIENT_ID=$okta_client_id \
    OKTA_CLIENT_SECRET=$okta_client_secret

CMD ["python3" "-m pip3" "list"]
