ARG ALLIANCE_RELEASE=latest
ARG REG=agrdocker
FROM ${REG}/agr_literature_env:${ALLIANCE_RELEASE}

ENV PROJECT_DIR /usr/local/bin/src/literature
ENV ENV_STATE test
WORKDIR ${PROJECT_DIR}

ADD . .

ARG aws_access_key_id=
ARG aws_secret_access_key=
ARG okta_client_id=
ARG okta_client_secret=

ENV API_PORT=8080 \
    AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
    AWS_ACCESS_KEY_ID=$aws_access_key_id \
    OKTA_CLIENT_ID=$okta_client_id \
    OKTA_CLIENT_SECRET=$okta_client_secret \
    PYTHONPATH="/workdir/src/xml_processing" \
    XML_PATH="/workdir/src/xml_processing/tests/" \
    ENV_STATE="test"

CMD ["python3", "backend/app/main.py", "--port=8080", "--ip-address=127.0.0.1"]
