ARG ALLIANCE_RELEASE=latest
ARG REG=agrdocker
FROM ${REG}/agr_base_linux_env:${ALLIANCE_RELEASE}

ADD backend/app/requirements.txt .

RUN apt install graphviz -y

RUN pip3 install -r requirements.txt

CMD ["python3" "-m pip3" "list"]
