ARG ALLIANCE_RELEASE=latest
ARG REG=agrdocker
FROM ${REG}/agr_literature_env:${ALLIANCE_RELEASE}

ADD backend/app/requirements.dev.txt .

RUN pip3 install -r requirements.dev.txt

RUN apt-get -y install zsh


#install posgres client
RUN apt-get -y install gnupg2
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
RUN apt-get update
RUN apt-get -y install postgresql-client-13


CMD ["python3" "-m pip3" "list"]
