"""
update_springer_oa_licenses.py
==============================
Update Resource table to add CC BY license for Springer Nature fully open access
journals that are currently missing license information.

This script reads from springer_oa_missing_licenses.tsv (generated by
check_springer_oa_licenses.py) and updates resources to set:
- license_list = ['CC BY']
- copyright_license_id = 1 (CC BY)

Usage:
    python update_springer_oa_licenses.py [--dry-run] [input_file]

Options:
    --dry-run    Show what would be updated without making changes
    input_file   TSV file with resource_id, title, eISSN (default: springer_oa_missing_licenses.tsv)
"""
import argparse
import logging
import sys
from os import path
from typing import List, Tuple

from sqlalchemy.orm import Session

from agr_literature_service.lit_processing.utils.sqlalchemy_utils import create_postgres_session
from agr_literature_service.api.models import ResourceModel
from agr_literature_service.api.user import set_global_user_id

logging.basicConfig(format="%(message)s")
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Default input file
DEFAULT_INPUT_FILE = "springer_oa_missing_licenses.tsv"

# CC BY license ID (most common Springer Nature OA license)
CC_BY_LICENSE_ID = 1
CC_BY_LICENSE_NAME = "CC BY"


def parse_input_file(input_file: str) -> List[Tuple[int, str, str]]:
    """
    Parse the TSV input file containing resource_id, title, eISSN.

    Returns:
        List of tuples (resource_id, title, eissn)
    """
    resources: List[Tuple[int, str, str]] = []

    if not path.exists(input_file):
        logger.error(f"Input file not found: {input_file}")
        return resources

    with open(input_file, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, start=1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            parts = line.split("\t")
            if len(parts) < 3:
                logger.warning(f"Line {line_num}: skipped (expected 3 columns, got {len(parts)})")
                continue

            try:
                resource_id = int(parts[0])
                title = parts[1]
                eissn = parts[2]
                resources.append((resource_id, title, eissn))
            except ValueError as e:
                logger.warning(f"Line {line_num}: skipped (invalid resource_id: {e})")
                continue

    return resources


def update_resources(db: Session, resources: List[Tuple[int, str, str]], dry_run: bool = False) -> None:
    """
    Update resources to add CC BY license information.

    Args:
        db: Database session
        resources: List of (resource_id, title, eissn) tuples
        dry_run: If True, don't commit changes
    """
    updated_count = 0
    not_found_count = 0
    already_licensed_count = 0
    error_count = 0

    for resource_id, title, eissn in resources:
        try:
            resource = db.query(ResourceModel).filter(
                ResourceModel.resource_id == resource_id
            ).first()

            if not resource:
                not_found_count += 1
                logger.warning(f"Resource not found: ID={resource_id}, Title={title}")
                continue

            # Check if already has license data
            if resource.license_list and len(resource.license_list) > 0:
                already_licensed_count += 1
                logger.info(f"Already has license: ID={resource_id}, {title[:50]} - {resource.license_list}")
                continue

            # Update resource with CC BY license
            if not dry_run:
                resource.license_list = [CC_BY_LICENSE_NAME]
                resource.copyright_license_id = CC_BY_LICENSE_ID
                db.add(resource)

            updated_count += 1
            action = "Would update" if dry_run else "Updated"
            logger.info(f"{action}: ID={resource_id}, {title[:60]} (eISSN: {eissn})")

        except Exception as e:
            error_count += 1
            logger.error(f"Error updating resource ID={resource_id}: {e}")

    # Commit all changes
    if not dry_run:
        db.commit()
        logger.info("Changes committed to database.")
    else:
        logger.info("DRY RUN - No changes were made.")

    logger.info("=" * 60)
    logger.info(f"Summary: Updated={updated_count}, Not found={not_found_count}, "
                f"Already licensed={already_licensed_count}, Errors={error_count}")


def main():
    parser = argparse.ArgumentParser(
        description="Update Springer Nature OA journals with CC BY license"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be updated without making changes"
    )
    parser.add_argument(
        "input_file",
        nargs="?",
        default=DEFAULT_INPUT_FILE,
        help=f"TSV file with resource_id, title, eISSN (default: {DEFAULT_INPUT_FILE})"
    )

    args = parser.parse_args()

    logger.info("Springer Nature OA License Update Script")
    logger.info(f"Input file: {args.input_file}")
    logger.info(f"Dry run: {args.dry_run}")
    logger.info("=" * 60)

    # Parse input file
    resources = parse_input_file(args.input_file)
    if not resources:
        logger.error("No resources to update. Exiting.")
        sys.exit(1)

    logger.info(f"Found {len(resources)} resources to process")

    # Connect to database
    db = create_postgres_session(False)

    # Set script user for audit trail
    script_name = path.basename(__file__).replace(".py", "")
    set_global_user_id(db, script_name)

    try:
        update_resources(db, resources, dry_run=args.dry_run)
    finally:
        db.close()


if __name__ == "__main__":
    main()
