"""change author-cross-reference cascade

Revision ID: 226a02bfa5b3
Revises: d7a2d9cd71dc
Create Date: 2022-03-28 14:51:40.424776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226a02bfa5b3'
down_revision = 'd7a2d9cd71dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_reference_id_fkey', 'authors', type_='foreignkey')
    op.create_foreign_key(None, 'authors', 'references', ['reference_id'], ['reference_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'authors', 'people', ['person_id'], ['person_id'])
    op.drop_constraint('cross_references_reference_id_fkey', 'cross_references', type_='foreignkey')
    op.create_foreign_key(None, 'cross_references', 'references', ['reference_id'], ['reference_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'editors', 'people', ['person_id'], ['person_id'])
    op.create_foreign_key(None, 'person_orcid_cross_reference_link', 'people', ['person_id'], ['person_id'])
    op.create_foreign_key(None, 'person_reference_link', 'people', ['person_id'], ['person_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person_reference_link', type_='foreignkey')
    op.drop_constraint(None, 'person_orcid_cross_reference_link', type_='foreignkey')
    op.drop_constraint(None, 'editors', type_='foreignkey')
    op.drop_constraint(None, 'cross_references', type_='foreignkey')
    op.create_foreign_key('cross_references_reference_id_fkey', 'cross_references', 'references', ['reference_id'], ['reference_id'])
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.create_foreign_key('authors_reference_id_fkey', 'authors', 'references', ['reference_id'], ['reference_id'])
    # ### end Alembic commands ###
