"""mesh_details table renamed

Revision ID: 9cb9da52a172
Revises: 1862a0356ece
Create Date: 2022-05-02 10:35:43.453509

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '9cb9da52a172'
down_revision = '1862a0356ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The table itself
    op.rename_table('mesh_details', 'mesh_detail')
    # its sequence
    op.execute('ALTER SEQUENCE mesh_details_mesh_detail_id_seq RENAME TO mesh_detail_mesh_detail_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX mesh_details_pkey RENAME TO mesh_detail_id_pkey')
    op.execute('ALTER INDEX ix_mesh_details_reference_id RENAME TO ix_mesh_detail_reference_id')

    # version
    op.rename_table('mesh_details_version', 'mesh_detail_version')
    # indexes
    op.execute('ALTER INDEX mesh_details_version_pkey RENAME TO mesh_detail_version_pkey')
    op.execute('ALTER INDEX ix_mesh_details_version_end_transaction_id RENAME TO ix_mesh_detail_version_end_transaction_id')
    op.execute('ALTER INDEX ix_mesh_details_version_operation_type RENAME TO ix_mesh_detail_version_operation_type')
    op.execute('ALTER INDEX ix_mesh_details_version_reference_id RENAME TO ix_mesh_detail_version_reference_id')
    op.execute('ALTER INDEX ix_mesh_details_version_transaction_id RENAME TO ix_mesh_detail_version_transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The table itself
    op.rename_table('mesh_detail', 'mesh_details')
    # its sequence
    op.execute('ALTER SEQUENCE mesh_detail_mesh_detail_id_seq RENAME TO mesh_details_mesh_details_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX mesh_detail_pkey RENAME TO mesh_details_id_pkey')
    op.execute('ALTER INDEX ix_mesh_detail_reference_id TO ix_mesh_details_reference_id')

    # version
    op.rename_table('mesh_detail_version', 'mesh_details_version')
    # indexes
    op.execute('ALTER INDEX mesh_detail_version_pkey RENAME TO mesh_details_version_pkey')
    op.execute('ALTER INDEX ix_mesh_detail_version_end_transaction_id RENAME TO ix_mesh_details_version_end_transaction_id')
    op.execute('ALTER INDEX ix_mesh_detail_version_operation_type RENAME TO ix_mesh_details_version_operation_type')
    op.execute('ALTER INDEX ix_mesh_detail_version_reference_id RENAME TO ix_mesh_details_version_reference_id')
    op.execute('ALTER INDEX ix_mesh_detail_version_transaction_id RENAME TO ix_mesh_details_version_transaction_id')
    # ### end Alembic commands ###
