"""add correction to reference category

Revision ID: be0be28b41aa
Revises: 951d7c11dbcd
Create Date: 2022-06-01 03:07:32.176122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0be28b41aa'
down_revision = '951d7c11dbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE referencecategory ADD VALUE IF NOT EXISTS 'Correction' AFTER 'Retraction'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
