"""mod_reference_types table renamed

Revision ID: d09597a053bb
Revises: 9cb9da52a172
Create Date: 2022-05-02 11:25:51.060333

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd09597a053bb'
down_revision = '9cb9da52a172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('mod_reference_types', 'mod_reference_type')
    # its sequence
    op.execute('ALTER SEQUENCE mod_reference_types_mod_reference_type_id_seq RENAME TO mod_reference_type_mod_reference_type_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX mod_reference_types_pkey RENAME TO mod_reference_type_pkey')
    op.execute('ALTER INDEX ix_mod_reference_types_reference_id RENAME TO ix_mod_reference_type_reference_id')

    op.rename_table('mod_reference_types_version', 'mod_reference_type_version')
    op.execute('ALTER INDEX mod_reference_types_version_pkey RENAME TO mod_reference_type_version_pkey')
    op.execute('ALTER INDEX ix_mod_reference_types_version_end_transaction_id RENAME TO ix_mod_reference_type_version_end_transaction_id')
    op.execute('ALTER INDEX ix_mod_reference_types_version_operation_type RENAME TO ix_mod_reference_type_version_operation_type')
    op.execute('ALTER INDEX ix_mod_reference_types_version_reference_id RENAME TO ix_mod_reference_type_version_reference_id')
    op.execute('ALTER INDEX ix_mod_reference_types_version_transaction_id RENAME TO ix_mod_reference_type_version_transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('mod_reference_type', 'mod_reference_types')
    # its sequence
    op.execute('ALTER SEQUENCE mod_reference_type_mod_reference_type_id_seq RENAME TO mod_reference_types_mod_reference_type_id_seq')
    # Its Indexes
    op.execute('ALTER INDEX mod_reference_type_pkey RENAME TO mod_reference_types_pkey')
    op.execute('ALTER INDEX ix_mod_reference_type_reference_id RENAME TO ix_mod_reference_types_reference_id')

    op.rename_table('mod_reference_type_version', 'mod_reference_type_version')
    op.execute('ALTER INDEX mod_reference_type_version_pkey RENAME TO mod_reference_types_version_pkey')
    op.execute('ALTER INDEX ix_mod_reference_type_version_end_transaction_id RENAME TO ix_mod_reference_types_version_end_transaction_id')
    op.execute('ALTER INDEX ix_mod_reference_type_version_operation_type RENAME TO ix_mod_reference_types_version_operation_type')
    op.execute('ALTER INDEX ix_mod_reference_type_version_reference_id RENAME TO ix_mod_reference_types_version_reference_id')
    op.execute('ALTER INDEX ix_mod_reference_type_version_transaction_id RENAME TO ix_mod_reference_types_version_transaction_id')

    # ### end Alembic commands ###
