"""Add a column open_access

Revision ID: d7a2d9cd71dc
Revises: 62c09ba92b8f
Create Date: 2021-10-27 11:48:51.111219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a2d9cd71dc'
down_revision = '62c09ba92b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('pubmed_publication_status', sa.Enum('ppublish', 'epublish', 'aheadofprint', name='pubmedpublicationstatus'), nullable=True))
    op.add_column('references', sa.Column('open_access', sa.Boolean(), nullable=False))
    op.add_column('references_version', sa.Column('pubmed_publication_status', sa.Enum('ppublish', 'epublish', 'aheadofprint', name='pubmedpublicationstatus'), autoincrement=False, nullable=True))
    op.add_column('references_version', sa.Column('open_access', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('references_version', sa.Column('pubmed_publication_status_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('references_version', sa.Column('open_access_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('resources', sa.Column('open_access', sa.Boolean(), nullable=False))
    op.add_column('resources_version', sa.Column('open_access', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('resources_version', sa.Column('open_access_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources_version', 'open_access_mod')
    op.drop_column('resources_version', 'open_access')
    op.drop_column('resources', 'open_access')
    op.drop_column('references_version', 'open_access_mod')
    op.drop_column('references_version', 'pubmed_publication_status_mod')
    op.drop_column('references_version', 'open_access')
    op.drop_column('references_version', 'pubmed_publication_status')
    op.drop_column('references', 'open_access')
    op.drop_column('references', 'pubmed_publication_status')
    # ### end Alembic commands ###
