name: unittest
on: [push]
jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        name: setup python
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/app/requirements.txt
          pip install -r backend/app/requirements.dev.txt
      - name: run unit_tests
        run: make run-test-bash
        continue-on-error: true