name: debezium-integration-test
on: 
  push:
    paths:
      - 'debezium/**'
      - 'tests/test_debezium_integration.py'
      - '.github/workflows/debezium-integration-test.yaml'
  pull_request:
    paths:
      - 'debezium/**'
      - 'tests/test_debezium_integration.py'
      - '.github/workflows/debezium-integration-test.yaml'

jobs:
  run-debezium-integration-tests:
    permissions:
      id-token: write # Required for AWS credentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-python@v4
        name: setup python
        with:
          python-version: 3.11
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
      
      - name: AWS credentials configuration
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.GH_ACTIONS_AWS_ROLE}}
          role-session-name: gh-actions-${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}-debezium-test
          aws-region: us-east-1
      
      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Start Debezium Infrastructure
        env:
          ENV_STATE: test
          HOST: 0.0.0.0
          PSQL_USERNAME: postgres
          PSQL_PASSWORD: postgres
          PSQL_HOST: localhost
          PSQL_PORT: 5432
          PSQL_DATABASE: literature-test
          ELASTICSEARCH_HOST: localhost
          ELASTICSEARCH_PORT: 9200
          DEBEZIUM_INDEX_NAME: test_references_index
          PUBLIC_INDEX_NAME: public_references_index
          DEBEZIUM_CONNECTOR_HOST: dbz_connector
          DEBEZIUM_CONNECTOR_PORT: 8083
          DEBEZIUM_KSQLDB_HOST: dbz_ksql_server
          DEBEZIUM_KSQLDB_PORT: 8088
          DEBEZIUM_VERSION: 3.0
          KAFKA_HEAP_OPTS: "-Xms2G -Xmx4G"
        run: |
          # Clean up any existing containers
          docker compose --env-file .env.test down -v
          
          # Start core infrastructure
          docker compose --env-file .env.test up -d postgres
          sleep 10
          
          # Initialize test database
          docker compose --env-file .env.test run --rm dev_app sh tests/init_test_db.sh
          
          # Start Elasticsearch
          docker compose --env-file .env.test up -d elasticsearch
          sleep 15
          
          # Start Kafka ecosystem
          docker compose --env-file .env.test up -d dbz_zookeeper dbz_kafka
          sleep 15
          
          # Start Debezium connector
          docker compose --env-file .env.test up -d dbz_connector
          sleep 20
          
          # Start KsqlDB
          docker compose --env-file .env.test up -d dbz_ksql_server
          sleep 25
      
      - name: Generate Mock Data
        env:
          ENV_STATE: test
          PYTHONPATH: agr_literature_service/lit_processing/
        run: |
          # Generate realistic mock data patterns (if RDS dev is accessible)
          python3 generate_mock_data.py || echo "Could not connect to RDS dev, using default patterns"
      
      - name: Setup Debezium Pipeline
        env:
          ENV_STATE: test
          PSQL_USERNAME: postgres
          PSQL_PASSWORD: postgres
          PSQL_HOST: localhost
          PSQL_PORT: 5432
          PSQL_DATABASE: literature-test
          ELASTICSEARCH_HOST: localhost
          ELASTICSEARCH_PORT: 9200
          DEBEZIUM_INDEX_NAME: test_references_index
          PUBLIC_INDEX_NAME: public_references_index
          DEBEZIUM_CONNECTOR_HOST: dbz_connector
          DEBEZIUM_CONNECTOR_PORT: 8083
          DEBEZIUM_KSQLDB_HOST: dbz_ksql_server
          DEBEZIUM_KSQLDB_PORT: 8088
        run: |
          # Wait for services to be ready
          sleep 30
          
          # Check service health
          docker compose --env-file .env.test ps
          
          # Setup Debezium connectors and KSQL streams
          timeout 300 bash -c 'until curl -f http://localhost:8083/connectors; do sleep 5; done'
          timeout 300 bash -c 'until curl -f http://localhost:8088/info; do sleep 5; done'
          
          # Run Debezium setup (simplified version)
          docker compose --env-file .env.test up -d --build dbz_setup || echo "Setup container finished"
          
          # Wait for data to be processed
          sleep 60
      
      - name: Run Debezium Integration Tests
        env:
          ENV_STATE: test
          PYTHONPATH: agr_literature_service/lit_processing/
          ELASTICSEARCH_HOST: localhost
          ELASTICSEARCH_PORT: 9200
          DEBEZIUM_INDEX_NAME: test_references_index
          PUBLIC_INDEX_NAME: public_references_index
          OKTA_DOMAIN: 'dev-30456587.okta.com/oauth2/default'
          OKTA_API_AUDIENCE: 'api://default'
          RESOURCE_DESCRIPTOR_URL: 'https://raw.githubusercontent.com/alliance-genome/agr_schemas/master/resourceDescriptors.yaml'
          OKTA_CLIENT_ID: ${{ secrets.okta_client_id }}
          OKTA_CLIENT_SECRET: ${{ secrets.okta_client_secret }}
        run: |
          # Run Debezium integration tests
          pytest tests/test_debezium_integration.py -v
          
          # Also run tests marked as webtest
          pytest tests/test_debezium_integration.py -m webtest -v
      
      - name: Debug Information
        if: failure()
        run: |
          echo "=== Docker Compose Status ==="
          docker compose --env-file .env.test ps
          
          echo "=== Elasticsearch Status ==="
          curl -s http://localhost:9200/_cat/health || echo "Elasticsearch not responding"
          curl -s http://localhost:9200/_cat/indices || echo "Could not get index info"
          
          echo "=== Kafka Connector Status ==="
          curl -s http://localhost:8083/connectors || echo "Connector not responding"
          
          echo "=== KsqlDB Status ==="
          curl -s http://localhost:8088/info || echo "KsqlDB not responding"
          
          echo "=== Container Logs ==="
          docker compose --env-file .env.test logs --tail=50 dbz_connector
          docker compose --env-file .env.test logs --tail=50 dbz_ksql_server
          docker compose --env-file .env.test logs --tail=50 elasticsearch
      
      - name: Cleanup
        if: always()
        run: |
          docker compose --env-file .env.test down -v